// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// ApplianceAPI は Appliance リソースに対する操作インターフェース。
type ApplianceAPI interface {
	Boot(ctx context.Context, zone string, id string) error
	Config(ctx context.Context, zone string, id string) error
	Create(ctx context.Context, zone string, request *client.ApplianceCreateRequestEnvelope) (*client.DatabaseCreateResponseEnvelope, error)
	Delete(ctx context.Context, zone string, id string) error
	List(ctx context.Context, zone string, q client.OptString) (*client.DatabaseFindResponseEnvelope, error)
	MonitorCPU(ctx context.Context, zone string, id string, request *client.MonitorCondition) (*client.DatabaseMonitorCPUResponseEnvelope, error)
	MonitorDatabase(ctx context.Context, zone string, id string, request *client.MonitorCondition) (*client.DatabaseMonitorDatabaseResponseEnvelope, error)
	MonitorInterface(ctx context.Context, zone string, id string, request *client.MonitorCondition) (*client.DatabaseMonitorInterfaceResponseEnvelope, error)
	MonitorInterfaceByIndex(ctx context.Context, zone string, id string, index string) (*client.MobileGatewayMonitorInterfaceResponseEnvelope, error)
	Read(ctx context.Context, zone string, id string) (*client.DatabaseReadResponseEnvelope, error)
	Reset(ctx context.Context, zone string, id string) error
	Shutdown(ctx context.Context, zone string, id string, request *client.ShutdownOption) error
	Status(ctx context.Context, zone string, id string) (*client.DatabaseStatusResponseEnvelope, error)
	Update(ctx context.Context, zone string, id string, request *client.ApplianceUpdateRequestEnvelope) (*client.DatabaseUpdateResponseEnvelope, error)
}

var _ ApplianceAPI = (*applianceOp)(nil)

type applianceOp struct {
	client *client.Client
}

// NewApplianceOp は ApplianceAPI 実装を返す。
func NewApplianceOp(c *client.Client) ApplianceAPI {
	return &applianceOp{client: c}
}

func (op *applianceOp) Boot(ctx context.Context, zone string, id string) error {
	params := client.ApplianceOpBootParams{Zone: zone, ID: id}
	_, err := op.client.ApplianceOpBoot(ctx, params)
	if err != nil {
		return wrapOpErr("Appliance.Boot", err)
	}
	return nil
}

func (op *applianceOp) Config(ctx context.Context, zone string, id string) error {
	params := client.ApplianceOpConfigParams{Zone: zone, ID: id}
	_, err := op.client.ApplianceOpConfig(ctx, params)
	if err != nil {
		return wrapOpErr("Appliance.Config", err)
	}
	return nil
}

func (op *applianceOp) Create(ctx context.Context, zone string, request *client.ApplianceCreateRequestEnvelope) (*client.DatabaseCreateResponseEnvelope, error) {
	params := client.ApplianceOpCreateParams{Zone: zone}
	resp, err := op.client.ApplianceOpCreate(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Appliance.Create", err)
	}
	return resp, nil
}

func (op *applianceOp) Delete(ctx context.Context, zone string, id string) error {
	params := client.ApplianceOpDeleteParams{Zone: zone, ID: id}
	_, err := op.client.ApplianceOpDelete(ctx, params)
	if err != nil {
		return wrapOpErr("Appliance.Delete", err)
	}
	return nil
}

func (op *applianceOp) List(ctx context.Context, zone string, q client.OptString) (*client.DatabaseFindResponseEnvelope, error) {
	params := client.ApplianceOpFindParams{Zone: zone, Q: q}
	resp, err := op.client.ApplianceOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Appliance.List", err)
	}
	return resp, nil
}

func (op *applianceOp) MonitorCPU(ctx context.Context, zone string, id string, request *client.MonitorCondition) (*client.DatabaseMonitorCPUResponseEnvelope, error) {
	params := client.ApplianceOpMonitorCPUParams{Zone: zone, ID: id}
	resp, err := op.client.ApplianceOpMonitorCPU(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Appliance.MonitorCPU", err)
	}
	return resp, nil
}

func (op *applianceOp) MonitorDatabase(ctx context.Context, zone string, id string, request *client.MonitorCondition) (*client.DatabaseMonitorDatabaseResponseEnvelope, error) {
	params := client.ApplianceOpMonitorDatabaseParams{Zone: zone, ID: id}
	resp, err := op.client.ApplianceOpMonitorDatabase(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Appliance.MonitorDatabase", err)
	}
	return resp, nil
}

func (op *applianceOp) MonitorInterface(ctx context.Context, zone string, id string, request *client.MonitorCondition) (*client.DatabaseMonitorInterfaceResponseEnvelope, error) {
	params := client.ApplianceOpMonitorInterfaceParams{Zone: zone, ID: id}
	resp, err := op.client.ApplianceOpMonitorInterface(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Appliance.MonitorInterface", err)
	}
	return resp, nil
}

func (op *applianceOp) MonitorInterfaceByIndex(ctx context.Context, zone string, id string, index string) (*client.MobileGatewayMonitorInterfaceResponseEnvelope, error) {
	params := client.ApplianceOpMonitorInterfaceByIndexParams{Zone: zone, ID: id, Index: index}
	resp, err := op.client.ApplianceOpMonitorInterfaceByIndex(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Appliance.MonitorInterfaceByIndex", err)
	}
	return resp, nil
}

func (op *applianceOp) Read(ctx context.Context, zone string, id string) (*client.DatabaseReadResponseEnvelope, error) {
	params := client.ApplianceOpReadParams{Zone: zone, ID: id}
	resp, err := op.client.ApplianceOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Appliance.Read", err)
	}
	return resp, nil
}

func (op *applianceOp) Reset(ctx context.Context, zone string, id string) error {
	params := client.ApplianceOpResetParams{Zone: zone, ID: id}
	_, err := op.client.ApplianceOpReset(ctx, params)
	if err != nil {
		return wrapOpErr("Appliance.Reset", err)
	}
	return nil
}

func (op *applianceOp) Shutdown(ctx context.Context, zone string, id string, request *client.ShutdownOption) error {
	params := client.ApplianceOpShutdownParams{Zone: zone, ID: id}
	_, err := op.client.ApplianceOpShutdown(ctx, request, params)
	if err != nil {
		return wrapOpErr("Appliance.Shutdown", err)
	}
	return nil
}

func (op *applianceOp) Status(ctx context.Context, zone string, id string) (*client.DatabaseStatusResponseEnvelope, error) {
	params := client.ApplianceOpStatusParams{Zone: zone, ID: id}
	resp, err := op.client.ApplianceOpStatus(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Appliance.Status", err)
	}
	return resp, nil
}

func (op *applianceOp) Update(ctx context.Context, zone string, id string, request *client.ApplianceUpdateRequestEnvelope) (*client.DatabaseUpdateResponseEnvelope, error) {
	params := client.ApplianceOpUpdateParams{Zone: zone, ID: id}
	resp, err := op.client.ApplianceOpUpdate(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Appliance.Update", err)
	}
	return resp, nil
}
