// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// ArchiveAPI は Archive リソースに対する操作インターフェース。
type ArchiveAPI interface {
	CloseFTP(ctx context.Context, id int64) error
	Create(ctx context.Context, request *client.ArchiveCreateRequestEnvelope) (*client.ArchiveCreateResponseEnvelope, error)
	Delete(ctx context.Context, id int64) error
	List(ctx context.Context, req *client.ArchiveFindRequest) (*client.ArchiveFindResponseEnvelope, error)
	Read(ctx context.Context, id int64) (*client.ArchiveReadResponseEnvelope, error)
	Share(ctx context.Context, id int64, request *client.ArchiveShareRequestEnvelope) (*client.ArchiveShareResponseEnvelope, error)
	Transfer(ctx context.Context, sourceArchiveID int64, destZoneID int64, request *client.ArchiveTransferRequestEnvelope) (*client.ArchiveTransferResponseEnvelope, error)
	Update(ctx context.Context, id int64, request *client.ArchiveUpdateRequestEnvelope) (*client.ArchiveUpdateResponseEnvelope, error)
}

var _ ArchiveAPI = (*archiveOp)(nil)

type archiveOp struct {
	client *client.Client
}

// NewArchiveOp は ArchiveAPI 実装を返す。
func NewArchiveOp(c *client.Client) ArchiveAPI {
	return &archiveOp{client: c}
}

func (op *archiveOp) CloseFTP(ctx context.Context, id int64) error {
	params := client.ArchiveOpCloseFTPParams{ID: id}
	_, err := op.client.ArchiveOpCloseFTP(ctx, params)
	if err != nil {
		return wrapOpErr("Archive.CloseFTP", err)
	}
	return nil
}

func (op *archiveOp) Create(ctx context.Context, request *client.ArchiveCreateRequestEnvelope) (*client.ArchiveCreateResponseEnvelope, error) {
	resp, err := op.client.ArchiveOpCreate(ctx, request)
	if err != nil {
		return nil, wrapOpErr("Archive.Create", err)
	}
	return resp, nil
}

func (op *archiveOp) Delete(ctx context.Context, id int64) error {
	params := client.ArchiveOpDeleteParams{ID: id}
	_, err := op.client.ArchiveOpDelete(ctx, params)
	if err != nil {
		return wrapOpErr("Archive.Delete", err)
	}
	return nil
}

func (op *archiveOp) List(ctx context.Context, req *client.ArchiveFindRequest) (*client.ArchiveFindResponseEnvelope, error) {
	params := client.ArchiveOpFindParams{}
	if req != nil {
		params.Q = req.ToOptString()
	}
	resp, err := op.client.ArchiveOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Archive.List", err)
	}
	return resp, nil
}

func (op *archiveOp) Read(ctx context.Context, id int64) (*client.ArchiveReadResponseEnvelope, error) {
	params := client.ArchiveOpReadParams{ID: id}
	resp, err := op.client.ArchiveOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Archive.Read", err)
	}
	return resp, nil
}

func (op *archiveOp) Share(ctx context.Context, id int64, request *client.ArchiveShareRequestEnvelope) (*client.ArchiveShareResponseEnvelope, error) {
	params := client.ArchiveOpShareParams{ID: id}
	resp, err := op.client.ArchiveOpShare(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Archive.Share", err)
	}
	return resp, nil
}

func (op *archiveOp) Transfer(ctx context.Context, sourceArchiveID int64, destZoneID int64, request *client.ArchiveTransferRequestEnvelope) (*client.ArchiveTransferResponseEnvelope, error) {
	params := client.ArchiveOpTransferParams{SourceArchiveID: sourceArchiveID, DestZoneID: destZoneID}
	resp, err := op.client.ArchiveOpTransfer(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Archive.Transfer", err)
	}
	return resp, nil
}

func (op *archiveOp) Update(ctx context.Context, id int64, request *client.ArchiveUpdateRequestEnvelope) (*client.ArchiveUpdateResponseEnvelope, error) {
	params := client.ArchiveOpUpdateParams{ID: id}
	resp, err := op.client.ArchiveOpUpdate(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Archive.Update", err)
	}
	return resp, nil
}
