// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// BillAPI は Bill リソースに対する操作インターフェース。
type BillAPI interface {
	ByContract(ctx context.Context, zone string, accountID string) (*client.BillByContractResponseEnvelope, error)
	ByContractYear(ctx context.Context, zone string, accountID string, year string) (*client.BillByContractYearResponseEnvelope, error)
	ByContractYearMonth(ctx context.Context, zone string, accountID string, year string, month string) (*client.BillByContractYearMonthResponseEnvelope, error)
	Details(ctx context.Context, zone string, memberCode string, id string) (*client.BillDetailsResponseEnvelope, error)
	DetailsCSV(ctx context.Context, zone string, memberCode string, id string) (*client.BillDetailsCSVResponseEnvelope, error)
	Read(ctx context.Context, zone string, id string) (*client.BillReadResponseEnvelope, error)
}

var _ BillAPI = (*billOp)(nil)

type billOp struct {
	client *client.Client
}

// NewBillOp は BillAPI 実装を返す。
func NewBillOp(c *client.Client) BillAPI {
	return &billOp{client: c}
}

func (op *billOp) ByContract(ctx context.Context, zone string, accountID string) (*client.BillByContractResponseEnvelope, error) {
	params := client.BillOpByContractParams{Zone: zone, AccountID: accountID}
	resp, err := op.client.BillOpByContract(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Bill.ByContract", err)
	}
	return resp, nil
}

func (op *billOp) ByContractYear(ctx context.Context, zone string, accountID string, year string) (*client.BillByContractYearResponseEnvelope, error) {
	params := client.BillOpByContractYearParams{Zone: zone, AccountID: accountID, Year: year}
	resp, err := op.client.BillOpByContractYear(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Bill.ByContractYear", err)
	}
	return resp, nil
}

func (op *billOp) ByContractYearMonth(ctx context.Context, zone string, accountID string, year string, month string) (*client.BillByContractYearMonthResponseEnvelope, error) {
	params := client.BillOpByContractYearMonthParams{Zone: zone, AccountID: accountID, Year: year, Month: month}
	resp, err := op.client.BillOpByContractYearMonth(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Bill.ByContractYearMonth", err)
	}
	return resp, nil
}

func (op *billOp) Details(ctx context.Context, zone string, memberCode string, id string) (*client.BillDetailsResponseEnvelope, error) {
	params := client.BillOpDetailsParams{Zone: zone, MemberCode: memberCode, ID: id}
	resp, err := op.client.BillOpDetails(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Bill.Details", err)
	}
	return resp, nil
}

func (op *billOp) DetailsCSV(ctx context.Context, zone string, memberCode string, id string) (*client.BillDetailsCSVResponseEnvelope, error) {
	params := client.BillOpDetailsCSVParams{Zone: zone, MemberCode: memberCode, ID: id}
	resp, err := op.client.BillOpDetailsCSV(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Bill.DetailsCSV", err)
	}
	return resp, nil
}

func (op *billOp) Read(ctx context.Context, zone string, id string) (*client.BillReadResponseEnvelope, error) {
	params := client.BillOpReadParams{Zone: zone, ID: id}
	resp, err := op.client.BillOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Bill.Read", err)
	}
	return resp, nil
}
