// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// BridgeAPI は Bridge リソースに対する操作インターフェース。
type BridgeAPI interface {
	Create(ctx context.Context, request *client.BridgeCreateRequestEnvelope) (*client.BridgeCreateResponseEnvelope, error)
	Delete(ctx context.Context, id string) error
	List(ctx context.Context, req *client.BridgeFindRequest) (*client.BridgeFindResponseEnvelope, error)
	Read(ctx context.Context, id string) (*client.BridgeReadResponseEnvelope, error)
	Update(ctx context.Context, id string, request *client.BridgeUpdateRequestEnvelope) (*client.BridgeUpdateResponseEnvelope, error)
}

var _ BridgeAPI = (*bridgeOp)(nil)

type bridgeOp struct {
	client *client.Client
}

// NewBridgeOp は BridgeAPI 実装を返す。
func NewBridgeOp(c *client.Client) BridgeAPI {
	return &bridgeOp{client: c}
}

func (op *bridgeOp) Create(ctx context.Context, request *client.BridgeCreateRequestEnvelope) (*client.BridgeCreateResponseEnvelope, error) {
	resp, err := op.client.BridgeOpCreate(ctx, request)
	if err != nil {
		return nil, wrapOpErr("Bridge.Create", err)
	}
	return resp, nil
}

func (op *bridgeOp) Delete(ctx context.Context, id string) error {
	params := client.BridgeOpDeleteParams{ID: id}
	_, err := op.client.BridgeOpDelete(ctx, params)
	if err != nil {
		return wrapOpErr("Bridge.Delete", err)
	}
	return nil
}

func (op *bridgeOp) List(ctx context.Context, req *client.BridgeFindRequest) (*client.BridgeFindResponseEnvelope, error) {
	params := client.BridgeOpFindParams{}
	if req != nil {
		params.Q = req.ToOptString()
	}
	resp, err := op.client.BridgeOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Bridge.List", err)
	}
	return resp, nil
}

func (op *bridgeOp) Read(ctx context.Context, id string) (*client.BridgeReadResponseEnvelope, error) {
	params := client.BridgeOpReadParams{ID: id}
	resp, err := op.client.BridgeOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Bridge.Read", err)
	}
	return resp, nil
}

func (op *bridgeOp) Update(ctx context.Context, id string, request *client.BridgeUpdateRequestEnvelope) (*client.BridgeUpdateResponseEnvelope, error) {
	params := client.BridgeOpUpdateParams{ID: id}
	resp, err := op.client.BridgeOpUpdate(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Bridge.Update", err)
	}
	return resp, nil
}
