// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// CertificateAuthorityAPI は CertificateAuthority リソースに対する操作インターフェース。
type CertificateAuthorityAPI interface {
	AddClient(ctx context.Context, zone string, id string, request *client.CertificateAuthorityOpAddClientReq) (*client.CertificateAuthorityAddClientResponseEnvelope, error)
	AddServer(ctx context.Context, zone string, id string, request *client.CertificateAuthorityOpAddServerReq) (*client.CertificateAuthorityAddServerResponseEnvelope, error)
	DenyClient(ctx context.Context, zone string, id string, clientID string) error
	Detail(ctx context.Context, zone string, id string) (*client.CertificateAuthorityDetailResponseEnvelope, error)
	HoldClient(ctx context.Context, zone string, id string, clientID string) error
	HoldServer(ctx context.Context, zone string, id string, serverID string) error
	ListClients(ctx context.Context, zone string, id string) (*client.CertificateAuthorityListClientsResponseEnvelope, error)
	ListServers(ctx context.Context, zone string, id string) (*client.CertificateAuthorityListServersResponseEnvelope, error)
	ReadClient(ctx context.Context, zone string, id string, clientID string) (*client.CertificateAuthorityReadClientResponseEnvelope, error)
	ReadServer(ctx context.Context, zone string, id string, serverID string) (*client.CertificateAuthorityReadServerResponseEnvelope, error)
	ResumeClient(ctx context.Context, zone string, id string, clientID string) error
	ResumeServer(ctx context.Context, zone string, id string, serverID string) error
	RevokeClient(ctx context.Context, zone string, id string, clientID string) error
	RevokeServer(ctx context.Context, zone string, id string, serverID string) error
}

var _ CertificateAuthorityAPI = (*certificateAuthorityOp)(nil)

type certificateAuthorityOp struct {
	client *client.Client
}

// NewCertificateAuthorityOp は CertificateAuthorityAPI 実装を返す。
func NewCertificateAuthorityOp(c *client.Client) CertificateAuthorityAPI {
	return &certificateAuthorityOp{client: c}
}

func (op *certificateAuthorityOp) AddClient(ctx context.Context, zone string, id string, request *client.CertificateAuthorityOpAddClientReq) (*client.CertificateAuthorityAddClientResponseEnvelope, error) {
	params := client.CertificateAuthorityOpAddClientParams{Zone: zone, ID: id}
	resp, err := op.client.CertificateAuthorityOpAddClient(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("CertificateAuthority.AddClient", err)
	}
	return resp, nil
}

func (op *certificateAuthorityOp) AddServer(ctx context.Context, zone string, id string, request *client.CertificateAuthorityOpAddServerReq) (*client.CertificateAuthorityAddServerResponseEnvelope, error) {
	params := client.CertificateAuthorityOpAddServerParams{Zone: zone, ID: id}
	resp, err := op.client.CertificateAuthorityOpAddServer(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("CertificateAuthority.AddServer", err)
	}
	return resp, nil
}

func (op *certificateAuthorityOp) DenyClient(ctx context.Context, zone string, id string, clientID string) error {
	params := client.CertificateAuthorityOpDenyClientParams{Zone: zone, ID: id, ClientID: clientID}
	_, err := op.client.CertificateAuthorityOpDenyClient(ctx, params)
	if err != nil {
		return wrapOpErr("CertificateAuthority.DenyClient", err)
	}
	return nil
}

func (op *certificateAuthorityOp) Detail(ctx context.Context, zone string, id string) (*client.CertificateAuthorityDetailResponseEnvelope, error) {
	params := client.CertificateAuthorityOpDetailParams{Zone: zone, ID: id}
	resp, err := op.client.CertificateAuthorityOpDetail(ctx, params)
	if err != nil {
		return nil, wrapOpErr("CertificateAuthority.Detail", err)
	}
	return resp, nil
}

func (op *certificateAuthorityOp) HoldClient(ctx context.Context, zone string, id string, clientID string) error {
	params := client.CertificateAuthorityOpHoldClientParams{Zone: zone, ID: id, ClientID: clientID}
	_, err := op.client.CertificateAuthorityOpHoldClient(ctx, params)
	if err != nil {
		return wrapOpErr("CertificateAuthority.HoldClient", err)
	}
	return nil
}

func (op *certificateAuthorityOp) HoldServer(ctx context.Context, zone string, id string, serverID string) error {
	params := client.CertificateAuthorityOpHoldServerParams{Zone: zone, ID: id, ServerID: serverID}
	_, err := op.client.CertificateAuthorityOpHoldServer(ctx, params)
	if err != nil {
		return wrapOpErr("CertificateAuthority.HoldServer", err)
	}
	return nil
}

func (op *certificateAuthorityOp) ListClients(ctx context.Context, zone string, id string) (*client.CertificateAuthorityListClientsResponseEnvelope, error) {
	params := client.CertificateAuthorityOpListClientsParams{Zone: zone, ID: id}
	resp, err := op.client.CertificateAuthorityOpListClients(ctx, params)
	if err != nil {
		return nil, wrapOpErr("CertificateAuthority.ListClients", err)
	}
	return resp, nil
}

func (op *certificateAuthorityOp) ListServers(ctx context.Context, zone string, id string) (*client.CertificateAuthorityListServersResponseEnvelope, error) {
	params := client.CertificateAuthorityOpListServersParams{Zone: zone, ID: id}
	resp, err := op.client.CertificateAuthorityOpListServers(ctx, params)
	if err != nil {
		return nil, wrapOpErr("CertificateAuthority.ListServers", err)
	}
	return resp, nil
}

func (op *certificateAuthorityOp) ReadClient(ctx context.Context, zone string, id string, clientID string) (*client.CertificateAuthorityReadClientResponseEnvelope, error) {
	params := client.CertificateAuthorityOpReadClientParams{Zone: zone, ID: id, ClientID: clientID}
	resp, err := op.client.CertificateAuthorityOpReadClient(ctx, params)
	if err != nil {
		return nil, wrapOpErr("CertificateAuthority.ReadClient", err)
	}
	return resp, nil
}

func (op *certificateAuthorityOp) ReadServer(ctx context.Context, zone string, id string, serverID string) (*client.CertificateAuthorityReadServerResponseEnvelope, error) {
	params := client.CertificateAuthorityOpReadServerParams{Zone: zone, ID: id, ServerID: serverID}
	resp, err := op.client.CertificateAuthorityOpReadServer(ctx, params)
	if err != nil {
		return nil, wrapOpErr("CertificateAuthority.ReadServer", err)
	}
	return resp, nil
}

func (op *certificateAuthorityOp) ResumeClient(ctx context.Context, zone string, id string, clientID string) error {
	params := client.CertificateAuthorityOpResumeClientParams{Zone: zone, ID: id, ClientID: clientID}
	_, err := op.client.CertificateAuthorityOpResumeClient(ctx, params)
	if err != nil {
		return wrapOpErr("CertificateAuthority.ResumeClient", err)
	}
	return nil
}

func (op *certificateAuthorityOp) ResumeServer(ctx context.Context, zone string, id string, serverID string) error {
	params := client.CertificateAuthorityOpResumeServerParams{Zone: zone, ID: id, ServerID: serverID}
	_, err := op.client.CertificateAuthorityOpResumeServer(ctx, params)
	if err != nil {
		return wrapOpErr("CertificateAuthority.ResumeServer", err)
	}
	return nil
}

func (op *certificateAuthorityOp) RevokeClient(ctx context.Context, zone string, id string, clientID string) error {
	params := client.CertificateAuthorityOpRevokeClientParams{Zone: zone, ID: id, ClientID: clientID}
	_, err := op.client.CertificateAuthorityOpRevokeClient(ctx, params)
	if err != nil {
		return wrapOpErr("CertificateAuthority.RevokeClient", err)
	}
	return nil
}

func (op *certificateAuthorityOp) RevokeServer(ctx context.Context, zone string, id string, serverID string) error {
	params := client.CertificateAuthorityOpRevokeServerParams{Zone: zone, ID: id, ServerID: serverID}
	_, err := op.client.CertificateAuthorityOpRevokeServer(ctx, params)
	if err != nil {
		return wrapOpErr("CertificateAuthority.RevokeServer", err)
	}
	return nil
}
