// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// CommonServiceItemAPI は CommonServiceItem リソースに対する操作インターフェース。
type CommonServiceItemAPI interface {
	Create(ctx context.Context, request *client.CommonServiceItemCreateRequestEnvelope) (*client.AutoBackupCreateResponseEnvelope, error)
	Delete(ctx context.Context, id int64) error
	List(ctx context.Context, q client.OptString) (*client.AutoBackupFindResponseEnvelope, error)
	HealthStatus(ctx context.Context, id int64) (*client.LocalRouterHealthStatusResponseEnvelope, error)
	Read(ctx context.Context, id int64) (*client.AutoBackupReadResponseEnvelope, error)
	Update(ctx context.Context, id int64, request *client.CommonServiceItemUpdateRequestEnvelope) (*client.AutoBackupUpdateResponseEnvelope, error)
}

var _ CommonServiceItemAPI = (*commonServiceItemOp)(nil)

type commonServiceItemOp struct {
	client *client.Client
}

// NewCommonServiceItemOp は CommonServiceItemAPI 実装を返す。
func NewCommonServiceItemOp(c *client.Client) CommonServiceItemAPI {
	return &commonServiceItemOp{client: c}
}

func (op *commonServiceItemOp) Create(ctx context.Context, request *client.CommonServiceItemCreateRequestEnvelope) (*client.AutoBackupCreateResponseEnvelope, error) {
	resp, err := op.client.CommonServiceItemOpCreate(ctx, request)
	if err != nil {
		return nil, wrapOpErr("CommonServiceItem.Create", err)
	}
	return resp, nil
}

func (op *commonServiceItemOp) Delete(ctx context.Context, id int64) error {
	params := client.CommonServiceItemOpDeleteParams{ID: id}
	_, err := op.client.CommonServiceItemOpDelete(ctx, params)
	if err != nil {
		return wrapOpErr("CommonServiceItem.Delete", err)
	}
	return nil
}

func (op *commonServiceItemOp) List(ctx context.Context, q client.OptString) (*client.AutoBackupFindResponseEnvelope, error) {
	params := client.CommonServiceItemOpFindParams{Q: q}
	resp, err := op.client.CommonServiceItemOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("CommonServiceItem.List", err)
	}
	return resp, nil
}

func (op *commonServiceItemOp) HealthStatus(ctx context.Context, id int64) (*client.LocalRouterHealthStatusResponseEnvelope, error) {
	params := client.CommonServiceItemOpHealthStatusParams{ID: id}
	resp, err := op.client.CommonServiceItemOpHealthStatus(ctx, params)
	if err != nil {
		return nil, wrapOpErr("CommonServiceItem.HealthStatus", err)
	}
	return resp, nil
}

func (op *commonServiceItemOp) Read(ctx context.Context, id int64) (*client.AutoBackupReadResponseEnvelope, error) {
	params := client.CommonServiceItemOpReadParams{ID: id}
	resp, err := op.client.CommonServiceItemOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("CommonServiceItem.Read", err)
	}
	return resp, nil
}

func (op *commonServiceItemOp) Update(ctx context.Context, id int64, request *client.CommonServiceItemUpdateRequestEnvelope) (*client.AutoBackupUpdateResponseEnvelope, error) {
	params := client.CommonServiceItemOpUpdateParams{ID: id}
	resp, err := op.client.CommonServiceItemOpUpdate(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("CommonServiceItem.Update", err)
	}
	return resp, nil
}
