// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// ContainerRegistryAPI は ContainerRegistry リソースに対する操作インターフェース。
type ContainerRegistryAPI interface {
	AddUser(ctx context.Context, id string, request *client.ContainerRegistryOpAddUserReq) error
	DeleteUser(ctx context.Context, id string, username string) error
	ListUsers(ctx context.Context, id string) (*client.ContainerRegistryListUsersResponseEnvelope, error)
	UpdateUser(ctx context.Context, id string, username string, request *client.ContainerRegistryOpUpdateUserReq) error
}

var _ ContainerRegistryAPI = (*containerRegistryOp)(nil)

type containerRegistryOp struct {
	client *client.Client
}

// NewContainerRegistryOp は ContainerRegistryAPI 実装を返す。
func NewContainerRegistryOp(c *client.Client) ContainerRegistryAPI {
	return &containerRegistryOp{client: c}
}

func (op *containerRegistryOp) AddUser(ctx context.Context, id string, request *client.ContainerRegistryOpAddUserReq) error {
	params := client.ContainerRegistryOpAddUserParams{ID: id}
	_, err := op.client.ContainerRegistryOpAddUser(ctx, request, params)
	if err != nil {
		return wrapOpErr("ContainerRegistry.AddUser", err)
	}
	return nil
}

func (op *containerRegistryOp) DeleteUser(ctx context.Context, id string, username string) error {
	params := client.ContainerRegistryOpDeleteUserParams{ID: id, Username: username}
	_, err := op.client.ContainerRegistryOpDeleteUser(ctx, params)
	if err != nil {
		return wrapOpErr("ContainerRegistry.DeleteUser", err)
	}
	return nil
}

func (op *containerRegistryOp) ListUsers(ctx context.Context, id string) (*client.ContainerRegistryListUsersResponseEnvelope, error) {
	params := client.ContainerRegistryOpListUsersParams{ID: id}
	resp, err := op.client.ContainerRegistryOpListUsers(ctx, params)
	if err != nil {
		return nil, wrapOpErr("ContainerRegistry.ListUsers", err)
	}
	return resp, nil
}

func (op *containerRegistryOp) UpdateUser(ctx context.Context, id string, username string, request *client.ContainerRegistryOpUpdateUserReq) error {
	params := client.ContainerRegistryOpUpdateUserParams{ID: id, Username: username}
	_, err := op.client.ContainerRegistryOpUpdateUser(ctx, request, params)
	if err != nil {
		return wrapOpErr("ContainerRegistry.UpdateUser", err)
	}
	return nil
}
