// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// CouponAPI は Coupon リソースに対する操作インターフェース。
type CouponAPI interface {
	List(ctx context.Context, accountID string) (*client.CouponFindResponseEnvelope, error)
}

var _ CouponAPI = (*couponOp)(nil)

type couponOp struct {
	client *client.Client
}

// NewCouponOp は CouponAPI 実装を返す。
func NewCouponOp(c *client.Client) CouponAPI {
	return &couponOp{client: c}
}

func (op *couponOp) List(ctx context.Context, accountID string) (*client.CouponFindResponseEnvelope, error) {
	params := client.CouponOpFindParams{AccountID: accountID}
	resp, err := op.client.CouponOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Coupon.List", err)
	}
	return resp, nil
}
