// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// DiskAPI は Disk リソースに対する操作インターフェース。
type DiskAPI interface {
	Config(ctx context.Context, id int64, request *client.DiskConfigRequestEnvelope) error
	ConnectToServer(ctx context.Context, id int64, serverID int64) error
	Create(ctx context.Context, request *client.DiskCreateRequestEnvelope) (*client.DiskCreateResponseEnvelope, error)
	Delete(ctx context.Context, id int64) error
	DisconnectFromServer(ctx context.Context, id int64) error
	List(ctx context.Context, req *client.DiskFindRequest) (*client.DiskFindResponseEnvelope, error)
	Monitor(ctx context.Context, id int64, request *client.DiskMonitorRequestEnvelope) (*client.DiskMonitorResponseEnvelope, error)
	Read(ctx context.Context, id int64) (*client.DiskReadResponseEnvelope, error)
	ResizePartition(ctx context.Context, id int64, request *client.DiskResizePartitionRequestEnvelope) error
	Update(ctx context.Context, id int64, request *client.DiskUpdateRequestEnvelope) (*client.DiskUpdateResponseEnvelope, error)
}

var _ DiskAPI = (*diskOp)(nil)

type diskOp struct {
	client *client.Client
}

// NewDiskOp は DiskAPI 実装を返す。
func NewDiskOp(c *client.Client) DiskAPI {
	return &diskOp{client: c}
}

func (op *diskOp) Config(ctx context.Context, id int64, request *client.DiskConfigRequestEnvelope) error {
	params := client.DiskOpConfigParams{ID: id}
	_, err := op.client.DiskOpConfig(ctx, request, params)
	if err != nil {
		return wrapOpErr("Disk.Config", err)
	}
	return nil
}

func (op *diskOp) ConnectToServer(ctx context.Context, id int64, serverID int64) error {
	params := client.DiskOpConnectToServerParams{ID: id, ServerID: serverID}
	_, err := op.client.DiskOpConnectToServer(ctx, params)
	if err != nil {
		return wrapOpErr("Disk.ConnectToServer", err)
	}
	return nil
}

func (op *diskOp) Create(ctx context.Context, request *client.DiskCreateRequestEnvelope) (*client.DiskCreateResponseEnvelope, error) {
	resp, err := op.client.DiskOpCreate(ctx, request)
	if err != nil {
		return nil, wrapOpErr("Disk.Create", err)
	}
	return resp, nil
}

func (op *diskOp) Delete(ctx context.Context, id int64) error {
	params := client.DiskOpDeleteParams{ID: id}
	_, err := op.client.DiskOpDelete(ctx, params)
	if err != nil {
		return wrapOpErr("Disk.Delete", err)
	}
	return nil
}

func (op *diskOp) DisconnectFromServer(ctx context.Context, id int64) error {
	params := client.DiskOpDisconnectFromServerParams{ID: id}
	_, err := op.client.DiskOpDisconnectFromServer(ctx, params)
	if err != nil {
		return wrapOpErr("Disk.DisconnectFromServer", err)
	}
	return nil
}

func (op *diskOp) List(ctx context.Context, req *client.DiskFindRequest) (*client.DiskFindResponseEnvelope, error) {
	params := client.DiskOpFindParams{}
	if req != nil {
		params.Q = req.ToOptString()
	}
	resp, err := op.client.DiskOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Disk.List", err)
	}
	return resp, nil
}

func (op *diskOp) Monitor(ctx context.Context, id int64, request *client.DiskMonitorRequestEnvelope) (*client.DiskMonitorResponseEnvelope, error) {
	params := client.DiskOpMonitorParams{ID: id}
	resp, err := op.client.DiskOpMonitor(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Disk.Monitor", err)
	}
	return resp, nil
}

func (op *diskOp) Read(ctx context.Context, id int64) (*client.DiskReadResponseEnvelope, error) {
	params := client.DiskOpReadParams{ID: id}
	resp, err := op.client.DiskOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Disk.Read", err)
	}
	return resp, nil
}

func (op *diskOp) ResizePartition(ctx context.Context, id int64, request *client.DiskResizePartitionRequestEnvelope) error {
	params := client.DiskOpResizePartitionParams{ID: id}
	_, err := op.client.DiskOpResizePartition(ctx, request, params)
	if err != nil {
		return wrapOpErr("Disk.ResizePartition", err)
	}
	return nil
}

func (op *diskOp) Update(ctx context.Context, id int64, request *client.DiskUpdateRequestEnvelope) (*client.DiskUpdateResponseEnvelope, error) {
	params := client.DiskOpUpdateParams{ID: id}
	resp, err := op.client.DiskOpUpdate(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Disk.Update", err)
	}
	return resp, nil
}
