// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// DiskPlanAPI は DiskPlan リソースに対する操作インターフェース。
type DiskPlanAPI interface {
	List(ctx context.Context, req *client.DiskPlanFindRequest) (*client.DiskPlanFindResponseEnvelope, error)
	Read(ctx context.Context, id string) (*client.DiskPlanReadResponseEnvelope, error)
}

var _ DiskPlanAPI = (*diskPlanOp)(nil)

type diskPlanOp struct {
	client *client.Client
}

// NewDiskPlanOp は DiskPlanAPI 実装を返す。
func NewDiskPlanOp(c *client.Client) DiskPlanAPI {
	return &diskPlanOp{client: c}
}

func (op *diskPlanOp) List(ctx context.Context, req *client.DiskPlanFindRequest) (*client.DiskPlanFindResponseEnvelope, error) {
	params := client.DiskPlanOpFindParams{}
	if req != nil {
		params.Q = req.ToOptString()
	}
	resp, err := op.client.DiskPlanOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("DiskPlan.List", err)
	}
	return resp, nil
}

func (op *diskPlanOp) Read(ctx context.Context, id string) (*client.DiskPlanReadResponseEnvelope, error) {
	params := client.DiskPlanOpReadParams{ID: id}
	resp, err := op.client.DiskPlanOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("DiskPlan.Read", err)
	}
	return resp, nil
}
