// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// IconAPI は Icon リソースに対する操作インターフェース。
type IconAPI interface {
	Create(ctx context.Context, request *client.IconCreateRequestEnvelope) (*client.IconCreateResponseEnvelope, error)
	Delete(ctx context.Context, id string) error
	List(ctx context.Context, req *client.IconFindRequest) (*client.IconFindResponseEnvelope, error)
	Read(ctx context.Context, id string) (*client.IconReadResponseEnvelope, error)
	Update(ctx context.Context, id string, request *client.IconUpdateRequestEnvelope) (*client.IconUpdateResponseEnvelope, error)
}

var _ IconAPI = (*iconOp)(nil)

type iconOp struct {
	client *client.Client
}

// NewIconOp は IconAPI 実装を返す。
func NewIconOp(c *client.Client) IconAPI {
	return &iconOp{client: c}
}

func (op *iconOp) Create(ctx context.Context, request *client.IconCreateRequestEnvelope) (*client.IconCreateResponseEnvelope, error) {
	resp, err := op.client.IconOpCreate(ctx, request)
	if err != nil {
		return nil, wrapOpErr("Icon.Create", err)
	}
	return resp, nil
}

func (op *iconOp) Delete(ctx context.Context, id string) error {
	params := client.IconOpDeleteParams{ID: id}
	_, err := op.client.IconOpDelete(ctx, params)
	if err != nil {
		return wrapOpErr("Icon.Delete", err)
	}
	return nil
}

func (op *iconOp) List(ctx context.Context, req *client.IconFindRequest) (*client.IconFindResponseEnvelope, error) {
	params := client.IconOpFindParams{}
	if req != nil {
		params.Q = req.ToOptString()
	}
	resp, err := op.client.IconOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Icon.List", err)
	}
	return resp, nil
}

func (op *iconOp) Read(ctx context.Context, id string) (*client.IconReadResponseEnvelope, error) {
	params := client.IconOpReadParams{ID: id}
	resp, err := op.client.IconOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Icon.Read", err)
	}
	return resp, nil
}

func (op *iconOp) Update(ctx context.Context, id string, request *client.IconUpdateRequestEnvelope) (*client.IconUpdateResponseEnvelope, error) {
	params := client.IconOpUpdateParams{ID: id}
	resp, err := op.client.IconOpUpdate(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Icon.Update", err)
	}
	return resp, nil
}
