// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// InternetAPI は Internet リソースに対する操作インターフェース。
type InternetAPI interface {
	AddSubnet(ctx context.Context, id string, request *client.InternetAddSubnetRequestEnvelope) (*client.InternetAddSubnetResponseEnvelope, error)
	Create(ctx context.Context, request *client.InternetCreateRequestEnvelope) (*client.InternetCreateResponseEnvelope, error)
	Delete(ctx context.Context, id string) error
	DeleteSubnet(ctx context.Context, id string, subnetID string) error
	DisableIPv6(ctx context.Context, id string, ipv6netID string) error
	EnableIPv6(ctx context.Context, id string) (*client.InternetEnableIPv6ResponseEnvelope, error)
	List(ctx context.Context, req *client.InternetFindRequest) (*client.InternetFindResponseEnvelope, error)
	Monitor(ctx context.Context, id string, request *client.InternetMonitorRequestEnvelope) (*client.InternetMonitorResponseEnvelope, error)
	Read(ctx context.Context, id string) (*client.InternetReadResponseEnvelope, error)
	Update(ctx context.Context, id string, request *client.InternetUpdateRequestEnvelope) (*client.InternetUpdateResponseEnvelope, error)
	UpdateBandWidth(ctx context.Context, id string, request *client.InternetUpdateBandWidthRequestEnvelope) (*client.InternetUpdateBandWidthResponseEnvelope, error)
	UpdateSubnet(ctx context.Context, id string, subnetID string, request *client.InternetUpdateSubnetRequestEnvelope) (*client.InternetUpdateSubnetResponseEnvelope, error)
}

var _ InternetAPI = (*internetOp)(nil)

type internetOp struct {
	client *client.Client
}

// NewInternetOp は InternetAPI 実装を返す。
func NewInternetOp(c *client.Client) InternetAPI {
	return &internetOp{client: c}
}

func (op *internetOp) AddSubnet(ctx context.Context, id string, request *client.InternetAddSubnetRequestEnvelope) (*client.InternetAddSubnetResponseEnvelope, error) {
	params := client.InternetOpAddSubnetParams{ID: id}
	resp, err := op.client.InternetOpAddSubnet(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Internet.AddSubnet", err)
	}
	return resp, nil
}

func (op *internetOp) Create(ctx context.Context, request *client.InternetCreateRequestEnvelope) (*client.InternetCreateResponseEnvelope, error) {
	resp, err := op.client.InternetOpCreate(ctx, request)
	if err != nil {
		return nil, wrapOpErr("Internet.Create", err)
	}
	return resp, nil
}

func (op *internetOp) Delete(ctx context.Context, id string) error {
	params := client.InternetOpDeleteParams{ID: id}
	_, err := op.client.InternetOpDelete(ctx, params)
	if err != nil {
		return wrapOpErr("Internet.Delete", err)
	}
	return nil
}

func (op *internetOp) DeleteSubnet(ctx context.Context, id string, subnetID string) error {
	params := client.InternetOpDeleteSubnetParams{ID: id, SubnetID: subnetID}
	_, err := op.client.InternetOpDeleteSubnet(ctx, params)
	if err != nil {
		return wrapOpErr("Internet.DeleteSubnet", err)
	}
	return nil
}

func (op *internetOp) DisableIPv6(ctx context.Context, id string, ipv6netID string) error {
	params := client.InternetOpDisableIPv6Params{ID: id, Ipv6netID: ipv6netID}
	_, err := op.client.InternetOpDisableIPv6(ctx, params)
	if err != nil {
		return wrapOpErr("Internet.DisableIPv6", err)
	}
	return nil
}

func (op *internetOp) EnableIPv6(ctx context.Context, id string) (*client.InternetEnableIPv6ResponseEnvelope, error) {
	params := client.InternetOpEnableIPv6Params{ID: id}
	resp, err := op.client.InternetOpEnableIPv6(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Internet.EnableIPv6", err)
	}
	return resp, nil
}

func (op *internetOp) List(ctx context.Context, req *client.InternetFindRequest) (*client.InternetFindResponseEnvelope, error) {
	params := client.InternetOpFindParams{}
	if req != nil {
		params.Q = req.ToOptString()
	}
	resp, err := op.client.InternetOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Internet.List", err)
	}
	return resp, nil
}

func (op *internetOp) Monitor(ctx context.Context, id string, request *client.InternetMonitorRequestEnvelope) (*client.InternetMonitorResponseEnvelope, error) {
	params := client.InternetOpMonitorParams{ID: id}
	resp, err := op.client.InternetOpMonitor(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Internet.Monitor", err)
	}
	return resp, nil
}

func (op *internetOp) Read(ctx context.Context, id string) (*client.InternetReadResponseEnvelope, error) {
	params := client.InternetOpReadParams{ID: id}
	resp, err := op.client.InternetOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Internet.Read", err)
	}
	return resp, nil
}

func (op *internetOp) Update(ctx context.Context, id string, request *client.InternetUpdateRequestEnvelope) (*client.InternetUpdateResponseEnvelope, error) {
	params := client.InternetOpUpdateParams{ID: id}
	resp, err := op.client.InternetOpUpdate(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Internet.Update", err)
	}
	return resp, nil
}

func (op *internetOp) UpdateBandWidth(ctx context.Context, id string, request *client.InternetUpdateBandWidthRequestEnvelope) (*client.InternetUpdateBandWidthResponseEnvelope, error) {
	params := client.InternetOpUpdateBandWidthParams{ID: id}
	resp, err := op.client.InternetOpUpdateBandWidth(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Internet.UpdateBandWidth", err)
	}
	return resp, nil
}

func (op *internetOp) UpdateSubnet(ctx context.Context, id string, subnetID string, request *client.InternetUpdateSubnetRequestEnvelope) (*client.InternetUpdateSubnetResponseEnvelope, error) {
	params := client.InternetOpUpdateSubnetParams{ID: id, SubnetID: subnetID}
	resp, err := op.client.InternetOpUpdateSubnet(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Internet.UpdateSubnet", err)
	}
	return resp, nil
}
