// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// InterfaceAPI は Interface リソースに対する操作インターフェース。
type InterfaceAPI interface {
	ConnectToPacketFilter(ctx context.Context, id int64, packetFilterID int64) error
	ConnectToSharedSegment(ctx context.Context, id int64) error
	ConnectToSwitch(ctx context.Context, id int64, switchID int64) error
	Create(ctx context.Context, request *client.InterfaceCreateRequestEnvelope) (*client.InterfaceCreateResponseEnvelope, error)
	Delete(ctx context.Context, id int64) error
	DisconnectFromPacketFilter(ctx context.Context, id int64) error
	DisconnectFromSwitch(ctx context.Context, id int64) error
	List(ctx context.Context, req *client.InterfaceFindRequest) (*client.InterfaceFindResponseEnvelope, error)
	Monitor(ctx context.Context, id int64, request *client.InterfaceMonitorRequestEnvelope) (*client.InterfaceMonitorResponseEnvelope, error)
	Read(ctx context.Context, id int64) (*client.InterfaceReadResponseEnvelope, error)
	Update(ctx context.Context, id int64, request *client.InterfaceUpdateRequestEnvelope) (*client.InterfaceUpdateResponseEnvelope, error)
}

var _ InterfaceAPI = (*interfaceOp)(nil)

type interfaceOp struct {
	client *client.Client
}

// NewInterfaceOp は InterfaceAPI 実装を返す。
func NewInterfaceOp(c *client.Client) InterfaceAPI {
	return &interfaceOp{client: c}
}

func (op *interfaceOp) ConnectToPacketFilter(ctx context.Context, id int64, packetFilterID int64) error {
	params := client.InterfaceOpConnectToPacketFilterParams{ID: id, PacketFilterID: packetFilterID}
	_, err := op.client.InterfaceOpConnectToPacketFilter(ctx, params)
	if err != nil {
		return wrapOpErr("Interface.ConnectToPacketFilter", err)
	}
	return nil
}

func (op *interfaceOp) ConnectToSharedSegment(ctx context.Context, id int64) error {
	params := client.InterfaceOpConnectToSharedSegmentParams{ID: id}
	_, err := op.client.InterfaceOpConnectToSharedSegment(ctx, params)
	if err != nil {
		return wrapOpErr("Interface.ConnectToSharedSegment", err)
	}
	return nil
}

func (op *interfaceOp) ConnectToSwitch(ctx context.Context, id int64, switchID int64) error {
	params := client.InterfaceOpConnectToSwitchParams{ID: id, SwitchID: switchID}
	_, err := op.client.InterfaceOpConnectToSwitch(ctx, params)
	if err != nil {
		return wrapOpErr("Interface.ConnectToSwitch", err)
	}
	return nil
}

func (op *interfaceOp) Create(ctx context.Context, request *client.InterfaceCreateRequestEnvelope) (*client.InterfaceCreateResponseEnvelope, error) {
	resp, err := op.client.InterfaceOpCreate(ctx, request)
	if err != nil {
		return nil, wrapOpErr("Interface.Create", err)
	}
	return resp, nil
}

func (op *interfaceOp) Delete(ctx context.Context, id int64) error {
	params := client.InterfaceOpDeleteParams{ID: id}
	_, err := op.client.InterfaceOpDelete(ctx, params)
	if err != nil {
		return wrapOpErr("Interface.Delete", err)
	}
	return nil
}

func (op *interfaceOp) DisconnectFromPacketFilter(ctx context.Context, id int64) error {
	params := client.InterfaceOpDisconnectFromPacketFilterParams{ID: id}
	_, err := op.client.InterfaceOpDisconnectFromPacketFilter(ctx, params)
	if err != nil {
		return wrapOpErr("Interface.DisconnectFromPacketFilter", err)
	}
	return nil
}

func (op *interfaceOp) DisconnectFromSwitch(ctx context.Context, id int64) error {
	params := client.InterfaceOpDisconnectFromSwitchParams{ID: id}
	_, err := op.client.InterfaceOpDisconnectFromSwitch(ctx, params)
	if err != nil {
		return wrapOpErr("Interface.DisconnectFromSwitch", err)
	}
	return nil
}

func (op *interfaceOp) List(ctx context.Context, req *client.InterfaceFindRequest) (*client.InterfaceFindResponseEnvelope, error) {
	params := client.InterfaceOpFindParams{}
	if req != nil {
		params.Q = req.ToOptString()
	}
	resp, err := op.client.InterfaceOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Interface.List", err)
	}
	return resp, nil
}

func (op *interfaceOp) Monitor(ctx context.Context, id int64, request *client.InterfaceMonitorRequestEnvelope) (*client.InterfaceMonitorResponseEnvelope, error) {
	params := client.InterfaceOpMonitorParams{ID: id}
	resp, err := op.client.InterfaceOpMonitor(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Interface.Monitor", err)
	}
	return resp, nil
}

func (op *interfaceOp) Read(ctx context.Context, id int64) (*client.InterfaceReadResponseEnvelope, error) {
	params := client.InterfaceOpReadParams{ID: id}
	resp, err := op.client.InterfaceOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Interface.Read", err)
	}
	return resp, nil
}

func (op *interfaceOp) Update(ctx context.Context, id int64, request *client.InterfaceUpdateRequestEnvelope) (*client.InterfaceUpdateResponseEnvelope, error) {
	params := client.InterfaceOpUpdateParams{ID: id}
	resp, err := op.client.InterfaceOpUpdate(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Interface.Update", err)
	}
	return resp, nil
}
