// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// IPAddressAPI は IPAddress リソースに対する操作インターフェース。
type IPAddressAPI interface {
	List(ctx context.Context, zone string) (*client.IPAddressListResponseEnvelope, error)
	Read(ctx context.Context, zone string, ipAddress string) (*client.IPAddressReadResponseEnvelope, error)
	UpdateHostName(ctx context.Context, zone string, ipAddress string, request *client.IPAddressUpdateHostNameRequestEnvelope) (*client.IPAddressUpdateHostNameResponseEnvelope, error)
}

var _ IPAddressAPI = (*iPAddressOp)(nil)

type iPAddressOp struct {
	client *client.Client
}

// NewIPAddressOp は IPAddressAPI 実装を返す。
func NewIPAddressOp(c *client.Client) IPAddressAPI {
	return &iPAddressOp{client: c}
}

func (op *iPAddressOp) List(ctx context.Context, zone string) (*client.IPAddressListResponseEnvelope, error) {
	params := client.IPAddressOpListParams{Zone: zone}
	resp, err := op.client.IPAddressOpList(ctx, params)
	if err != nil {
		return nil, wrapOpErr("IPAddress.List", err)
	}
	return resp, nil
}

func (op *iPAddressOp) Read(ctx context.Context, zone string, ipAddress string) (*client.IPAddressReadResponseEnvelope, error) {
	params := client.IPAddressOpReadParams{Zone: zone, IpAddress: ipAddress}
	resp, err := op.client.IPAddressOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("IPAddress.Read", err)
	}
	return resp, nil
}

func (op *iPAddressOp) UpdateHostName(ctx context.Context, zone string, ipAddress string, request *client.IPAddressUpdateHostNameRequestEnvelope) (*client.IPAddressUpdateHostNameResponseEnvelope, error) {
	params := client.IPAddressOpUpdateHostNameParams{Zone: zone, IpAddress: ipAddress}
	resp, err := op.client.IPAddressOpUpdateHostName(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("IPAddress.UpdateHostName", err)
	}
	return resp, nil
}
