// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// IPv6NetAPI は IPv6Net リソースに対する操作インターフェース。
type IPv6NetAPI interface {
	List(ctx context.Context, request *client.IPv6NetListRequestEnvelope) (*client.IPv6NetListResponseEnvelope, error)
	Read(ctx context.Context, id string) (*client.IPv6NetReadResponseEnvelope, error)
}

var _ IPv6NetAPI = (*iPv6NetOp)(nil)

type iPv6NetOp struct {
	client *client.Client
}

// NewIPv6NetOp は IPv6NetAPI 実装を返す。
func NewIPv6NetOp(c *client.Client) IPv6NetAPI {
	return &iPv6NetOp{client: c}
}

func (op *iPv6NetOp) List(ctx context.Context, request *client.IPv6NetListRequestEnvelope) (*client.IPv6NetListResponseEnvelope, error) {
	resp, err := op.client.IPv6NetOpList(ctx, request)
	if err != nil {
		return nil, wrapOpErr("IPv6Net.List", err)
	}
	return resp, nil
}

func (op *iPv6NetOp) Read(ctx context.Context, id string) (*client.IPv6NetReadResponseEnvelope, error) {
	params := client.IPv6NetOpReadParams{ID: id}
	resp, err := op.client.IPv6NetOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("IPv6Net.Read", err)
	}
	return resp, nil
}
