// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// LicenseAPI は License リソースに対する操作インターフェース。
type LicenseAPI interface {
	Create(ctx context.Context, zone string, request *client.LicenseCreateRequestEnvelope) (*client.LicenseCreateResponseEnvelope, error)
	Delete(ctx context.Context, zone string, id string) error
	List(ctx context.Context, zone string, req *client.LicenseFindRequest) (*client.LicenseFindResponseEnvelope, error)
	Read(ctx context.Context, zone string, id string) (*client.LicenseReadResponseEnvelope, error)
	Update(ctx context.Context, zone string, id string, request *client.LicenseUpdateRequestEnvelope) (*client.LicenseUpdateResponseEnvelope, error)
}

var _ LicenseAPI = (*licenseOp)(nil)

type licenseOp struct {
	client *client.Client
}

// NewLicenseOp は LicenseAPI 実装を返す。
func NewLicenseOp(c *client.Client) LicenseAPI {
	return &licenseOp{client: c}
}

func (op *licenseOp) Create(ctx context.Context, zone string, request *client.LicenseCreateRequestEnvelope) (*client.LicenseCreateResponseEnvelope, error) {
	params := client.LicenseOpCreateParams{Zone: zone}
	resp, err := op.client.LicenseOpCreate(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("License.Create", err)
	}
	return resp, nil
}

func (op *licenseOp) Delete(ctx context.Context, zone string, id string) error {
	params := client.LicenseOpDeleteParams{Zone: zone, ID: id}
	_, err := op.client.LicenseOpDelete(ctx, params)
	if err != nil {
		return wrapOpErr("License.Delete", err)
	}
	return nil
}

func (op *licenseOp) List(ctx context.Context, zone string, req *client.LicenseFindRequest) (*client.LicenseFindResponseEnvelope, error) {
	params := client.LicenseOpFindParams{Zone: zone}
	if req != nil {
		params.Q = req.ToOptString()
	}
	resp, err := op.client.LicenseOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("License.List", err)
	}
	return resp, nil
}

func (op *licenseOp) Read(ctx context.Context, zone string, id string) (*client.LicenseReadResponseEnvelope, error) {
	params := client.LicenseOpReadParams{Zone: zone, ID: id}
	resp, err := op.client.LicenseOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("License.Read", err)
	}
	return resp, nil
}

func (op *licenseOp) Update(ctx context.Context, zone string, id string, request *client.LicenseUpdateRequestEnvelope) (*client.LicenseUpdateResponseEnvelope, error) {
	params := client.LicenseOpUpdateParams{Zone: zone, ID: id}
	resp, err := op.client.LicenseOpUpdate(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("License.Update", err)
	}
	return resp, nil
}
