// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// LicenseInfoAPI は LicenseInfo リソースに対する操作インターフェース。
type LicenseInfoAPI interface {
	List(ctx context.Context, req *client.LicenseInfoFindRequest) (*client.LicenseInfoFindResponseEnvelope, error)
	Read(ctx context.Context, id int64) (*client.LicenseInfoReadResponseEnvelope, error)
}

var _ LicenseInfoAPI = (*licenseInfoOp)(nil)

type licenseInfoOp struct {
	client *client.Client
}

// NewLicenseInfoOp は LicenseInfoAPI 実装を返す。
func NewLicenseInfoOp(c *client.Client) LicenseInfoAPI {
	return &licenseInfoOp{client: c}
}

func (op *licenseInfoOp) List(ctx context.Context, req *client.LicenseInfoFindRequest) (*client.LicenseInfoFindResponseEnvelope, error) {
	params := client.LicenseInfoOpFindParams{}
	if req != nil {
		params.Q = req.ToOptString()
	}
	resp, err := op.client.LicenseInfoOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("LicenseInfo.List", err)
	}
	return resp, nil
}

func (op *licenseInfoOp) Read(ctx context.Context, id int64) (*client.LicenseInfoReadResponseEnvelope, error) {
	params := client.LicenseInfoOpReadParams{ID: id}
	resp, err := op.client.LicenseInfoOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("LicenseInfo.Read", err)
	}
	return resp, nil
}
