// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// MobileGatewayAPI は MobileGateway リソースに対する操作インターフェース。
type MobileGatewayAPI interface {
	AddSIM(ctx context.Context, id string, request *client.MobileGatewayOpAddSIMReq) error
	ConnectToSwitch(ctx context.Context, id string, switchID string) error
	DeleteSIM(ctx context.Context, id string, simID string) error
	DeleteTrafficConfig(ctx context.Context, id string) error
	DisconnectFromSwitch(ctx context.Context, id string) error
	GetDNS(ctx context.Context, id string) (*client.MobileGatewayGetDNSResponseEnvelope, error)
	GetSIMRoutes(ctx context.Context, id string) (*client.MobileGatewayGetSIMRoutesResponseEnvelope, error)
	GetTrafficConfig(ctx context.Context, id string) (*client.MobileGatewayGetTrafficConfigResponseEnvelope, error)
	ListSIM(ctx context.Context, id string) (*client.MobileGatewayListSIMResponseEnvelope, error)
	Logs(ctx context.Context, id string) (*client.MobileGatewayLogsResponseEnvelope, error)
	SetDNS(ctx context.Context, id string, request *client.MobileGatewayOpSetDNSReq) error
	SetSIMRoutes(ctx context.Context, id string, request *client.MobileGatewayOpSetSIMRoutesReq) error
	SetTrafficConfig(ctx context.Context, id string, request *client.MobileGatewayOpSetTrafficConfigReq) error
	TrafficStatus(ctx context.Context, id string) (*client.MobileGatewayTrafficStatusResponseEnvelope, error)
}

var _ MobileGatewayAPI = (*mobileGatewayOp)(nil)

type mobileGatewayOp struct {
	client *client.Client
}

// NewMobileGatewayOp は MobileGatewayAPI 実装を返す。
func NewMobileGatewayOp(c *client.Client) MobileGatewayAPI {
	return &mobileGatewayOp{client: c}
}

func (op *mobileGatewayOp) AddSIM(ctx context.Context, id string, request *client.MobileGatewayOpAddSIMReq) error {
	params := client.MobileGatewayOpAddSIMParams{ID: id}
	_, err := op.client.MobileGatewayOpAddSIM(ctx, request, params)
	if err != nil {
		return wrapOpErr("MobileGateway.AddSIM", err)
	}
	return nil
}

func (op *mobileGatewayOp) ConnectToSwitch(ctx context.Context, id string, switchID string) error {
	params := client.MobileGatewayOpConnectToSwitchParams{ID: id, SwitchID: switchID}
	_, err := op.client.MobileGatewayOpConnectToSwitch(ctx, params)
	if err != nil {
		return wrapOpErr("MobileGateway.ConnectToSwitch", err)
	}
	return nil
}

func (op *mobileGatewayOp) DeleteSIM(ctx context.Context, id string, simID string) error {
	params := client.MobileGatewayOpDeleteSIMParams{ID: id, SimID: simID}
	_, err := op.client.MobileGatewayOpDeleteSIM(ctx, params)
	if err != nil {
		return wrapOpErr("MobileGateway.DeleteSIM", err)
	}
	return nil
}

func (op *mobileGatewayOp) DeleteTrafficConfig(ctx context.Context, id string) error {
	params := client.MobileGatewayOpDeleteTrafficConfigParams{ID: id}
	_, err := op.client.MobileGatewayOpDeleteTrafficConfig(ctx, params)
	if err != nil {
		return wrapOpErr("MobileGateway.DeleteTrafficConfig", err)
	}
	return nil
}

func (op *mobileGatewayOp) DisconnectFromSwitch(ctx context.Context, id string) error {
	params := client.MobileGatewayOpDisconnectFromSwitchParams{ID: id}
	_, err := op.client.MobileGatewayOpDisconnectFromSwitch(ctx, params)
	if err != nil {
		return wrapOpErr("MobileGateway.DisconnectFromSwitch", err)
	}
	return nil
}

func (op *mobileGatewayOp) GetDNS(ctx context.Context, id string) (*client.MobileGatewayGetDNSResponseEnvelope, error) {
	params := client.MobileGatewayOpGetDNSParams{ID: id}
	resp, err := op.client.MobileGatewayOpGetDNS(ctx, params)
	if err != nil {
		return nil, wrapOpErr("MobileGateway.GetDNS", err)
	}
	return resp, nil
}

func (op *mobileGatewayOp) GetSIMRoutes(ctx context.Context, id string) (*client.MobileGatewayGetSIMRoutesResponseEnvelope, error) {
	params := client.MobileGatewayOpGetSIMRoutesParams{ID: id}
	resp, err := op.client.MobileGatewayOpGetSIMRoutes(ctx, params)
	if err != nil {
		return nil, wrapOpErr("MobileGateway.GetSIMRoutes", err)
	}
	return resp, nil
}

func (op *mobileGatewayOp) GetTrafficConfig(ctx context.Context, id string) (*client.MobileGatewayGetTrafficConfigResponseEnvelope, error) {
	params := client.MobileGatewayOpGetTrafficConfigParams{ID: id}
	resp, err := op.client.MobileGatewayOpGetTrafficConfig(ctx, params)
	if err != nil {
		return nil, wrapOpErr("MobileGateway.GetTrafficConfig", err)
	}
	return resp, nil
}

func (op *mobileGatewayOp) ListSIM(ctx context.Context, id string) (*client.MobileGatewayListSIMResponseEnvelope, error) {
	params := client.MobileGatewayOpListSIMParams{ID: id}
	resp, err := op.client.MobileGatewayOpListSIM(ctx, params)
	if err != nil {
		return nil, wrapOpErr("MobileGateway.ListSIM", err)
	}
	return resp, nil
}

func (op *mobileGatewayOp) Logs(ctx context.Context, id string) (*client.MobileGatewayLogsResponseEnvelope, error) {
	params := client.MobileGatewayOpLogsParams{ID: id}
	resp, err := op.client.MobileGatewayOpLogs(ctx, params)
	if err != nil {
		return nil, wrapOpErr("MobileGateway.Logs", err)
	}
	return resp, nil
}

func (op *mobileGatewayOp) SetDNS(ctx context.Context, id string, request *client.MobileGatewayOpSetDNSReq) error {
	params := client.MobileGatewayOpSetDNSParams{ID: id}
	_, err := op.client.MobileGatewayOpSetDNS(ctx, request, params)
	if err != nil {
		return wrapOpErr("MobileGateway.SetDNS", err)
	}
	return nil
}

func (op *mobileGatewayOp) SetSIMRoutes(ctx context.Context, id string, request *client.MobileGatewayOpSetSIMRoutesReq) error {
	params := client.MobileGatewayOpSetSIMRoutesParams{ID: id}
	_, err := op.client.MobileGatewayOpSetSIMRoutes(ctx, request, params)
	if err != nil {
		return wrapOpErr("MobileGateway.SetSIMRoutes", err)
	}
	return nil
}

func (op *mobileGatewayOp) SetTrafficConfig(ctx context.Context, id string, request *client.MobileGatewayOpSetTrafficConfigReq) error {
	params := client.MobileGatewayOpSetTrafficConfigParams{ID: id}
	_, err := op.client.MobileGatewayOpSetTrafficConfig(ctx, request, params)
	if err != nil {
		return wrapOpErr("MobileGateway.SetTrafficConfig", err)
	}
	return nil
}

func (op *mobileGatewayOp) TrafficStatus(ctx context.Context, id string) (*client.MobileGatewayTrafficStatusResponseEnvelope, error) {
	params := client.MobileGatewayOpTrafficStatusParams{ID: id}
	resp, err := op.client.MobileGatewayOpTrafficStatus(ctx, params)
	if err != nil {
		return nil, wrapOpErr("MobileGateway.TrafficStatus", err)
	}
	return resp, nil
}
