// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// NoteAPI は Note リソースに対する操作インターフェース。
type NoteAPI interface {
	Create(ctx context.Context, request *client.NoteCreateRequestEnvelope) (*client.NoteCreateResponseEnvelope, error)
	Delete(ctx context.Context, id int64) error
	List(ctx context.Context, req *client.NoteFindRequest) (*client.NoteFindResponseEnvelope, error)
	Read(ctx context.Context, id int64) (*client.NoteReadResponseEnvelope, error)
	Update(ctx context.Context, id int64, request *client.NoteUpdateRequestEnvelope) (*client.NoteUpdateResponseEnvelope, error)
}

var _ NoteAPI = (*noteOp)(nil)

type noteOp struct {
	client *client.Client
}

// NewNoteOp は NoteAPI 実装を返す。
func NewNoteOp(c *client.Client) NoteAPI {
	return &noteOp{client: c}
}

func (op *noteOp) Create(ctx context.Context, request *client.NoteCreateRequestEnvelope) (*client.NoteCreateResponseEnvelope, error) {
	resp, err := op.client.NoteOpCreate(ctx, request)
	if err != nil {
		return nil, wrapOpErr("Note.Create", err)
	}
	return resp, nil
}

func (op *noteOp) Delete(ctx context.Context, id int64) error {
	params := client.NoteOpDeleteParams{ID: id}
	_, err := op.client.NoteOpDelete(ctx, params)
	if err != nil {
		return wrapOpErr("Note.Delete", err)
	}
	return nil
}

func (op *noteOp) List(ctx context.Context, req *client.NoteFindRequest) (*client.NoteFindResponseEnvelope, error) {
	params := client.NoteOpFindParams{}
	if req != nil {
		params.Q = req.ToOptString()
	}
	resp, err := op.client.NoteOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Note.List", err)
	}
	return resp, nil
}

func (op *noteOp) Read(ctx context.Context, id int64) (*client.NoteReadResponseEnvelope, error) {
	params := client.NoteOpReadParams{ID: id}
	resp, err := op.client.NoteOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Note.Read", err)
	}
	return resp, nil
}

func (op *noteOp) Update(ctx context.Context, id int64, request *client.NoteUpdateRequestEnvelope) (*client.NoteUpdateResponseEnvelope, error) {
	params := client.NoteOpUpdateParams{ID: id}
	resp, err := op.client.NoteOpUpdate(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Note.Update", err)
	}
	return resp, nil
}
