// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// PacketFilterAPI は PacketFilter リソースに対する操作インターフェース。
type PacketFilterAPI interface {
	Create(ctx context.Context, request *client.PacketFilterCreateRequestEnvelope) (*client.PacketFilterCreateResponseEnvelope, error)
	Delete(ctx context.Context, id string) error
	List(ctx context.Context, req *client.PacketFilterFindRequest) (*client.PacketFilterFindResponseEnvelope, error)
	Read(ctx context.Context, id string) (*client.PacketFilterReadResponseEnvelope, error)
	Update(ctx context.Context, id string, request *client.PacketFilterUpdateRequestEnvelope) (*client.PacketFilterUpdateResponseEnvelope, error)
}

var _ PacketFilterAPI = (*packetFilterOp)(nil)

type packetFilterOp struct {
	client *client.Client
}

// NewPacketFilterOp は PacketFilterAPI 実装を返す。
func NewPacketFilterOp(c *client.Client) PacketFilterAPI {
	return &packetFilterOp{client: c}
}

func (op *packetFilterOp) Create(ctx context.Context, request *client.PacketFilterCreateRequestEnvelope) (*client.PacketFilterCreateResponseEnvelope, error) {
	resp, err := op.client.PacketFilterOpCreate(ctx, request)
	if err != nil {
		return nil, wrapOpErr("PacketFilter.Create", err)
	}
	return resp, nil
}

func (op *packetFilterOp) Delete(ctx context.Context, id string) error {
	params := client.PacketFilterOpDeleteParams{ID: id}
	_, err := op.client.PacketFilterOpDelete(ctx, params)
	if err != nil {
		return wrapOpErr("PacketFilter.Delete", err)
	}
	return nil
}

func (op *packetFilterOp) List(ctx context.Context, req *client.PacketFilterFindRequest) (*client.PacketFilterFindResponseEnvelope, error) {
	params := client.PacketFilterOpFindParams{}
	if req != nil {
		params.Q = req.ToOptString()
	}
	resp, err := op.client.PacketFilterOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("PacketFilter.List", err)
	}
	return resp, nil
}

func (op *packetFilterOp) Read(ctx context.Context, id string) (*client.PacketFilterReadResponseEnvelope, error) {
	params := client.PacketFilterOpReadParams{ID: id}
	resp, err := op.client.PacketFilterOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("PacketFilter.Read", err)
	}
	return resp, nil
}

func (op *packetFilterOp) Update(ctx context.Context, id string, request *client.PacketFilterUpdateRequestEnvelope) (*client.PacketFilterUpdateResponseEnvelope, error) {
	params := client.PacketFilterOpUpdateParams{ID: id}
	resp, err := op.client.PacketFilterOpUpdate(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("PacketFilter.Update", err)
	}
	return resp, nil
}
