// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// PrivateHostPlanAPI は PrivateHostPlan リソースに対する操作インターフェース。
type PrivateHostPlanAPI interface {
	List(ctx context.Context, req *client.PrivateHostPlanFindRequest) (*client.PrivateHostPlanFindResponseEnvelope, error)
	Read(ctx context.Context, id string) (*client.PrivateHostPlanReadResponseEnvelope, error)
}

var _ PrivateHostPlanAPI = (*privateHostPlanOp)(nil)

type privateHostPlanOp struct {
	client *client.Client
}

// NewPrivateHostPlanOp は PrivateHostPlanAPI 実装を返す。
func NewPrivateHostPlanOp(c *client.Client) PrivateHostPlanAPI {
	return &privateHostPlanOp{client: c}
}

func (op *privateHostPlanOp) List(ctx context.Context, req *client.PrivateHostPlanFindRequest) (*client.PrivateHostPlanFindResponseEnvelope, error) {
	params := client.PrivateHostPlanOpFindParams{}
	if req != nil {
		params.Q = req.ToOptString()
	}
	resp, err := op.client.PrivateHostPlanOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("PrivateHostPlan.List", err)
	}
	return resp, nil
}

func (op *privateHostPlanOp) Read(ctx context.Context, id string) (*client.PrivateHostPlanReadResponseEnvelope, error) {
	params := client.PrivateHostPlanOpReadParams{ID: id}
	resp, err := op.client.PrivateHostPlanOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("PrivateHostPlan.Read", err)
	}
	return resp, nil
}
