// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// PrivateHostAPI は PrivateHost リソースに対する操作インターフェース。
type PrivateHostAPI interface {
	Create(ctx context.Context, request *client.PrivateHostCreateRequestEnvelope) (*client.PrivateHostCreateResponseEnvelope, error)
	Delete(ctx context.Context, id string) error
	List(ctx context.Context, req *client.PrivateHostFindRequest) (*client.PrivateHostFindResponseEnvelope, error)
	Read(ctx context.Context, id string) (*client.PrivateHostReadResponseEnvelope, error)
	Update(ctx context.Context, id string, request *client.PrivateHostUpdateRequestEnvelope) (*client.PrivateHostUpdateResponseEnvelope, error)
}

var _ PrivateHostAPI = (*privateHostOp)(nil)

type privateHostOp struct {
	client *client.Client
}

// NewPrivateHostOp は PrivateHostAPI 実装を返す。
func NewPrivateHostOp(c *client.Client) PrivateHostAPI {
	return &privateHostOp{client: c}
}

func (op *privateHostOp) Create(ctx context.Context, request *client.PrivateHostCreateRequestEnvelope) (*client.PrivateHostCreateResponseEnvelope, error) {
	resp, err := op.client.PrivateHostOpCreate(ctx, request)
	if err != nil {
		return nil, wrapOpErr("PrivateHost.Create", err)
	}
	return resp, nil
}

func (op *privateHostOp) Delete(ctx context.Context, id string) error {
	params := client.PrivateHostOpDeleteParams{ID: id}
	_, err := op.client.PrivateHostOpDelete(ctx, params)
	if err != nil {
		return wrapOpErr("PrivateHost.Delete", err)
	}
	return nil
}

func (op *privateHostOp) List(ctx context.Context, req *client.PrivateHostFindRequest) (*client.PrivateHostFindResponseEnvelope, error) {
	params := client.PrivateHostOpFindParams{}
	if req != nil {
		params.Q = req.ToOptString()
	}
	resp, err := op.client.PrivateHostOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("PrivateHost.List", err)
	}
	return resp, nil
}

func (op *privateHostOp) Read(ctx context.Context, id string) (*client.PrivateHostReadResponseEnvelope, error) {
	params := client.PrivateHostOpReadParams{ID: id}
	resp, err := op.client.PrivateHostOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("PrivateHost.Read", err)
	}
	return resp, nil
}

func (op *privateHostOp) Update(ctx context.Context, id string, request *client.PrivateHostUpdateRequestEnvelope) (*client.PrivateHostUpdateResponseEnvelope, error) {
	params := client.PrivateHostOpUpdateParams{ID: id}
	resp, err := op.client.PrivateHostOpUpdate(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("PrivateHost.Update", err)
	}
	return resp, nil
}
