// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// ProxyLBAPI は ProxyLB リソースに対する操作インターフェース。
type ProxyLBAPI interface {
	ChangePlan(ctx context.Context, id int64, request *client.ProxyLBOpChangePlanReq) (*client.ProxyLBChangePlanResponseEnvelope, error)
	DeleteCertificates(ctx context.Context, id int64) error
	GetCertificates(ctx context.Context, id int64) (*client.ProxyLBGetCertificatesResponseEnvelope, error)
	MonitorConnection(ctx context.Context, id int64, request *client.ProxyLBOpMonitorConnectionReq) (*client.ProxyLBMonitorConnectionResponseEnvelope, error)
	RenewLetsEncryptCert(ctx context.Context, id int64) error
	SetCertificates(ctx context.Context, id int64, request *client.ProxyLBOpSetCertificatesReq) (*client.ProxyLBSetCertificatesResponseEnvelope, error)
}

var _ ProxyLBAPI = (*proxyLBOp)(nil)

type proxyLBOp struct {
	client *client.Client
}

// NewProxyLBOp は ProxyLBAPI 実装を返す。
func NewProxyLBOp(c *client.Client) ProxyLBAPI {
	return &proxyLBOp{client: c}
}

func (op *proxyLBOp) ChangePlan(ctx context.Context, id int64, request *client.ProxyLBOpChangePlanReq) (*client.ProxyLBChangePlanResponseEnvelope, error) {
	params := client.ProxyLBOpChangePlanParams{ID: id}
	resp, err := op.client.ProxyLBOpChangePlan(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("ProxyLB.ChangePlan", err)
	}
	return resp, nil
}

func (op *proxyLBOp) DeleteCertificates(ctx context.Context, id int64) error {
	params := client.ProxyLBOpDeleteCertificatesParams{ID: id}
	_, err := op.client.ProxyLBOpDeleteCertificates(ctx, params)
	if err != nil {
		return wrapOpErr("ProxyLB.DeleteCertificates", err)
	}
	return nil
}

func (op *proxyLBOp) GetCertificates(ctx context.Context, id int64) (*client.ProxyLBGetCertificatesResponseEnvelope, error) {
	params := client.ProxyLBOpGetCertificatesParams{ID: id}
	resp, err := op.client.ProxyLBOpGetCertificates(ctx, params)
	if err != nil {
		return nil, wrapOpErr("ProxyLB.GetCertificates", err)
	}
	return resp, nil
}

func (op *proxyLBOp) MonitorConnection(ctx context.Context, id int64, request *client.ProxyLBOpMonitorConnectionReq) (*client.ProxyLBMonitorConnectionResponseEnvelope, error) {
	params := client.ProxyLBOpMonitorConnectionParams{ID: id}
	resp, err := op.client.ProxyLBOpMonitorConnection(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("ProxyLB.MonitorConnection", err)
	}
	return resp, nil
}

func (op *proxyLBOp) RenewLetsEncryptCert(ctx context.Context, id int64) error {
	params := client.ProxyLBOpRenewLetsEncryptCertParams{ID: id}
	_, err := op.client.ProxyLBOpRenewLetsEncryptCert(ctx, params)
	if err != nil {
		return wrapOpErr("ProxyLB.RenewLetsEncryptCert", err)
	}
	return nil
}

func (op *proxyLBOp) SetCertificates(ctx context.Context, id int64, request *client.ProxyLBOpSetCertificatesReq) (*client.ProxyLBSetCertificatesResponseEnvelope, error) {
	params := client.ProxyLBOpSetCertificatesParams{ID: id}
	resp, err := op.client.ProxyLBOpSetCertificates(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("ProxyLB.SetCertificates", err)
	}
	return resp, nil
}
