// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// ServerAPI は Server リソースに対する操作インターフェース。
type ServerAPI interface {
	Boot(ctx context.Context, zone string, id string, request *client.ServerBootRequestEnvelope) error
	ChangePlan(ctx context.Context, zone string, id string, request *client.ServerChangePlanRequestEnvelope) (*client.ServerChangePlanResponseEnvelope, error)
	Create(ctx context.Context, zone string, request *client.ServerCreateRequestEnvelope) (*client.ServerCreateResponseEnvelope, error)
	Delete(ctx context.Context, zone string, id string, request *client.ServerDeleteRequestEnvelope) error
	EjectCDROM(ctx context.Context, zone string, id string, request *client.ServerEjectCDROMRequestEnvelope) error
	List(ctx context.Context, zone string, req *client.ServerFindRequest) (*client.ServerFindResponseEnvelope, error)
	GetVNCProxy(ctx context.Context, zone string, id string) (*client.ServerGetVNCProxyResponseEnvelope, error)
	InsertCDROM(ctx context.Context, zone string, id string, request *client.ServerInsertCDROMRequestEnvelope) error
	Monitor(ctx context.Context, zone string, id string, request *client.ServerMonitorRequestEnvelope) (*client.ServerMonitorResponseEnvelope, error)
	Read(ctx context.Context, zone string, id string) (*client.ServerReadResponseEnvelope, error)
	Reset(ctx context.Context, zone string, id string) error
	SendKey(ctx context.Context, zone string, id string, request *client.ServerSendKeyRequestEnvelope) error
	SendNMI(ctx context.Context, zone string, id string) error
	Shutdown(ctx context.Context, zone string, id string, request *client.ServerShutdownRequestEnvelope) error
	Update(ctx context.Context, zone string, id string, request *client.ServerUpdateRequestEnvelope) (*client.ServerUpdateResponseEnvelope, error)
}

var _ ServerAPI = (*serverOp)(nil)

type serverOp struct {
	client *client.Client
}

// NewServerOp は ServerAPI 実装を返す。
func NewServerOp(c *client.Client) ServerAPI {
	return &serverOp{client: c}
}

func (op *serverOp) Boot(ctx context.Context, zone string, id string, request *client.ServerBootRequestEnvelope) error {
	params := client.ServerOpBootParams{Zone: zone, ID: id}
	_, err := op.client.ServerOpBoot(ctx, request, params)
	if err != nil {
		return wrapOpErr("Server.Boot", err)
	}
	return nil
}

func (op *serverOp) ChangePlan(ctx context.Context, zone string, id string, request *client.ServerChangePlanRequestEnvelope) (*client.ServerChangePlanResponseEnvelope, error) {
	params := client.ServerOpChangePlanParams{Zone: zone, ID: id}
	resp, err := op.client.ServerOpChangePlan(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Server.ChangePlan", err)
	}
	return resp, nil
}

func (op *serverOp) Create(ctx context.Context, zone string, request *client.ServerCreateRequestEnvelope) (*client.ServerCreateResponseEnvelope, error) {
	params := client.ServerOpCreateParams{Zone: zone}
	resp, err := op.client.ServerOpCreate(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Server.Create", err)
	}
	return resp, nil
}

func (op *serverOp) Delete(ctx context.Context, zone string, id string, request *client.ServerDeleteRequestEnvelope) error {
	params := client.ServerOpDeleteParams{Zone: zone, ID: id}
	_, err := op.client.ServerOpDelete(ctx, request, params)
	if err != nil {
		return wrapOpErr("Server.Delete", err)
	}
	return nil
}

func (op *serverOp) EjectCDROM(ctx context.Context, zone string, id string, request *client.ServerEjectCDROMRequestEnvelope) error {
	params := client.ServerOpEjectCDROMParams{Zone: zone, ID: id}
	_, err := op.client.ServerOpEjectCDROM(ctx, request, params)
	if err != nil {
		return wrapOpErr("Server.EjectCDROM", err)
	}
	return nil
}

func (op *serverOp) List(ctx context.Context, zone string, req *client.ServerFindRequest) (*client.ServerFindResponseEnvelope, error) {
	params := client.ServerOpFindParams{Zone: zone}
	if req != nil {
		params.Q = req.ToOptString()
	}
	resp, err := op.client.ServerOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Server.List", err)
	}
	return resp, nil
}

func (op *serverOp) GetVNCProxy(ctx context.Context, zone string, id string) (*client.ServerGetVNCProxyResponseEnvelope, error) {
	params := client.ServerOpGetVNCProxyParams{Zone: zone, ID: id}
	resp, err := op.client.ServerOpGetVNCProxy(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Server.GetVNCProxy", err)
	}
	return resp, nil
}

func (op *serverOp) InsertCDROM(ctx context.Context, zone string, id string, request *client.ServerInsertCDROMRequestEnvelope) error {
	params := client.ServerOpInsertCDROMParams{Zone: zone, ID: id}
	_, err := op.client.ServerOpInsertCDROM(ctx, request, params)
	if err != nil {
		return wrapOpErr("Server.InsertCDROM", err)
	}
	return nil
}

func (op *serverOp) Monitor(ctx context.Context, zone string, id string, request *client.ServerMonitorRequestEnvelope) (*client.ServerMonitorResponseEnvelope, error) {
	params := client.ServerOpMonitorParams{Zone: zone, ID: id}
	resp, err := op.client.ServerOpMonitor(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Server.Monitor", err)
	}
	return resp, nil
}

func (op *serverOp) Read(ctx context.Context, zone string, id string) (*client.ServerReadResponseEnvelope, error) {
	params := client.ServerOpReadParams{Zone: zone, ID: id}
	resp, err := op.client.ServerOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Server.Read", err)
	}
	return resp, nil
}

func (op *serverOp) Reset(ctx context.Context, zone string, id string) error {
	params := client.ServerOpResetParams{Zone: zone, ID: id}
	_, err := op.client.ServerOpReset(ctx, params)
	if err != nil {
		return wrapOpErr("Server.Reset", err)
	}
	return nil
}

func (op *serverOp) SendKey(ctx context.Context, zone string, id string, request *client.ServerSendKeyRequestEnvelope) error {
	params := client.ServerOpSendKeyParams{Zone: zone, ID: id}
	_, err := op.client.ServerOpSendKey(ctx, request, params)
	if err != nil {
		return wrapOpErr("Server.SendKey", err)
	}
	return nil
}

func (op *serverOp) SendNMI(ctx context.Context, zone string, id string) error {
	params := client.ServerOpSendNMIParams{Zone: zone, ID: id}
	_, err := op.client.ServerOpSendNMI(ctx, params)
	if err != nil {
		return wrapOpErr("Server.SendNMI", err)
	}
	return nil
}

func (op *serverOp) Shutdown(ctx context.Context, zone string, id string, request *client.ServerShutdownRequestEnvelope) error {
	params := client.ServerOpShutdownParams{Zone: zone, ID: id}
	_, err := op.client.ServerOpShutdown(ctx, request, params)
	if err != nil {
		return wrapOpErr("Server.Shutdown", err)
	}
	return nil
}

func (op *serverOp) Update(ctx context.Context, zone string, id string, request *client.ServerUpdateRequestEnvelope) (*client.ServerUpdateResponseEnvelope, error) {
	params := client.ServerOpUpdateParams{Zone: zone, ID: id}
	resp, err := op.client.ServerOpUpdate(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Server.Update", err)
	}
	return resp, nil
}
