// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// SimpleNotificationDestinationAPI は SimpleNotificationDestination リソースに対する操作インターフェース。
type SimpleNotificationDestinationAPI interface {
	Status(ctx context.Context, zone string, id string) (*client.SimpleNotificationDestinationStatusResponseEnvelope, error)
}

var _ SimpleNotificationDestinationAPI = (*simpleNotificationDestinationOp)(nil)

type simpleNotificationDestinationOp struct {
	client *client.Client
}

// NewSimpleNotificationDestinationOp は SimpleNotificationDestinationAPI 実装を返す。
func NewSimpleNotificationDestinationOp(c *client.Client) SimpleNotificationDestinationAPI {
	return &simpleNotificationDestinationOp{client: c}
}

func (op *simpleNotificationDestinationOp) Status(ctx context.Context, zone string, id string) (*client.SimpleNotificationDestinationStatusResponseEnvelope, error) {
	params := client.SimpleNotificationDestinationOpStatusParams{Zone: zone, ID: id}
	resp, err := op.client.SimpleNotificationDestinationOpStatus(ctx, params)
	if err != nil {
		return nil, wrapOpErr("SimpleNotificationDestination.Status", err)
	}
	return resp, nil
}
