// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// SimpleNotificationGroupAPI は SimpleNotificationGroup リソースに対する操作インターフェース。
type SimpleNotificationGroupAPI interface {
	History(ctx context.Context) (*client.SimpleNotificationGroupHistoryResponseEnvelope, error)
	PostMessage(ctx context.Context, id string, request *client.SimpleNotificationGroupOpPostMessageReq) error
}

var _ SimpleNotificationGroupAPI = (*simpleNotificationGroupOp)(nil)

type simpleNotificationGroupOp struct {
	client *client.Client
}

// NewSimpleNotificationGroupOp は SimpleNotificationGroupAPI 実装を返す。
func NewSimpleNotificationGroupOp(c *client.Client) SimpleNotificationGroupAPI {
	return &simpleNotificationGroupOp{client: c}
}

func (op *simpleNotificationGroupOp) History(ctx context.Context) (*client.SimpleNotificationGroupHistoryResponseEnvelope, error) {
	resp, err := op.client.SimpleNotificationGroupOpHistory(ctx)
	if err != nil {
		return nil, wrapOpErr("SimpleNotificationGroup.History", err)
	}
	return resp, nil
}

func (op *simpleNotificationGroupOp) PostMessage(ctx context.Context, id string, request *client.SimpleNotificationGroupOpPostMessageReq) error {
	params := client.SimpleNotificationGroupOpPostMessageParams{ID: id}
	_, err := op.client.SimpleNotificationGroupOpPostMessage(ctx, request, params)
	if err != nil {
		return wrapOpErr("SimpleNotificationGroup.PostMessage", err)
	}
	return nil
}
