// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// SSHKeyAPI は SSHKey リソースに対する操作インターフェース。
type SSHKeyAPI interface {
	Create(ctx context.Context, zone string, request *client.SSHKeyCreateRequestEnvelope) (*client.SSHKeyCreateResponseEnvelope, error)
	Delete(ctx context.Context, zone string, id string) error
	List(ctx context.Context, zone string, req *client.SSHKeyFindRequest) (*client.SSHKeyFindResponseEnvelope, error)
	Read(ctx context.Context, zone string, id string) (*client.SSHKeyReadResponseEnvelope, error)
	Update(ctx context.Context, zone string, id string, request *client.SSHKeyUpdateRequestEnvelope) (*client.SSHKeyUpdateResponseEnvelope, error)
}

var _ SSHKeyAPI = (*sSHKeyOp)(nil)

type sSHKeyOp struct {
	client *client.Client
}

// NewSSHKeyOp は SSHKeyAPI 実装を返す。
func NewSSHKeyOp(c *client.Client) SSHKeyAPI {
	return &sSHKeyOp{client: c}
}

func (op *sSHKeyOp) Create(ctx context.Context, zone string, request *client.SSHKeyCreateRequestEnvelope) (*client.SSHKeyCreateResponseEnvelope, error) {
	params := client.SSHKeyOpCreateParams{Zone: zone}
	resp, err := op.client.SSHKeyOpCreate(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("SSHKey.Create", err)
	}
	return resp, nil
}

func (op *sSHKeyOp) Delete(ctx context.Context, zone string, id string) error {
	params := client.SSHKeyOpDeleteParams{Zone: zone, ID: id}
	_, err := op.client.SSHKeyOpDelete(ctx, params)
	if err != nil {
		return wrapOpErr("SSHKey.Delete", err)
	}
	return nil
}

func (op *sSHKeyOp) List(ctx context.Context, zone string, req *client.SSHKeyFindRequest) (*client.SSHKeyFindResponseEnvelope, error) {
	params := client.SSHKeyOpFindParams{Zone: zone}
	if req != nil {
		params.Q = req.ToOptString()
	}
	resp, err := op.client.SSHKeyOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("SSHKey.List", err)
	}
	return resp, nil
}

func (op *sSHKeyOp) Read(ctx context.Context, zone string, id string) (*client.SSHKeyReadResponseEnvelope, error) {
	params := client.SSHKeyOpReadParams{Zone: zone, ID: id}
	resp, err := op.client.SSHKeyOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("SSHKey.Read", err)
	}
	return resp, nil
}

func (op *sSHKeyOp) Update(ctx context.Context, zone string, id string, request *client.SSHKeyUpdateRequestEnvelope) (*client.SSHKeyUpdateResponseEnvelope, error) {
	params := client.SSHKeyOpUpdateParams{Zone: zone, ID: id}
	resp, err := op.client.SSHKeyOpUpdate(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("SSHKey.Update", err)
	}
	return resp, nil
}
