// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// SwitchAPI は Switch リソースに対する操作インターフェース。
type SwitchAPI interface {
	ConnectToBridge(ctx context.Context, id string, bridgeID string) error
	Create(ctx context.Context, request *client.SwitchCreateRequestEnvelope) (*client.SwitchCreateResponseEnvelope, error)
	Delete(ctx context.Context, id string) error
	DisconnectFromBridge(ctx context.Context, id string) error
	List(ctx context.Context, req *client.SwitchFindRequest) (*client.SwitchFindResponseEnvelope, error)
	GetServers(ctx context.Context, id string) (*client.SwitchGetServersResponseEnvelope, error)
	Read(ctx context.Context, id string) (*client.SwitchReadResponseEnvelope, error)
	Update(ctx context.Context, id string, request *client.SwitchUpdateRequestEnvelope) (*client.SwitchUpdateResponseEnvelope, error)
}

var _ SwitchAPI = (*switchOp)(nil)

type switchOp struct {
	client *client.Client
}

// NewSwitchOp は SwitchAPI 実装を返す。
func NewSwitchOp(c *client.Client) SwitchAPI {
	return &switchOp{client: c}
}

func (op *switchOp) ConnectToBridge(ctx context.Context, id string, bridgeID string) error {
	params := client.SwitchOpConnectToBridgeParams{ID: id, BridgeID: bridgeID}
	_, err := op.client.SwitchOpConnectToBridge(ctx, params)
	if err != nil {
		return wrapOpErr("Switch.ConnectToBridge", err)
	}
	return nil
}

func (op *switchOp) Create(ctx context.Context, request *client.SwitchCreateRequestEnvelope) (*client.SwitchCreateResponseEnvelope, error) {
	resp, err := op.client.SwitchOpCreate(ctx, request)
	if err != nil {
		return nil, wrapOpErr("Switch.Create", err)
	}
	return resp, nil
}

func (op *switchOp) Delete(ctx context.Context, id string) error {
	params := client.SwitchOpDeleteParams{ID: id}
	_, err := op.client.SwitchOpDelete(ctx, params)
	if err != nil {
		return wrapOpErr("Switch.Delete", err)
	}
	return nil
}

func (op *switchOp) DisconnectFromBridge(ctx context.Context, id string) error {
	params := client.SwitchOpDisconnectFromBridgeParams{ID: id}
	_, err := op.client.SwitchOpDisconnectFromBridge(ctx, params)
	if err != nil {
		return wrapOpErr("Switch.DisconnectFromBridge", err)
	}
	return nil
}

func (op *switchOp) List(ctx context.Context, req *client.SwitchFindRequest) (*client.SwitchFindResponseEnvelope, error) {
	params := client.SwitchOpFindParams{}
	if req != nil {
		params.Q = req.ToOptString()
	}
	resp, err := op.client.SwitchOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Switch.List", err)
	}
	return resp, nil
}

func (op *switchOp) GetServers(ctx context.Context, id string) (*client.SwitchGetServersResponseEnvelope, error) {
	params := client.SwitchOpGetServersParams{ID: id}
	resp, err := op.client.SwitchOpGetServers(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Switch.GetServers", err)
	}
	return resp, nil
}

func (op *switchOp) Read(ctx context.Context, id string) (*client.SwitchReadResponseEnvelope, error) {
	params := client.SwitchOpReadParams{ID: id}
	resp, err := op.client.SwitchOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Switch.Read", err)
	}
	return resp, nil
}

func (op *switchOp) Update(ctx context.Context, id string, request *client.SwitchUpdateRequestEnvelope) (*client.SwitchUpdateResponseEnvelope, error) {
	params := client.SwitchOpUpdateParams{ID: id}
	resp, err := op.client.SwitchOpUpdate(ctx, request, params)
	if err != nil {
		return nil, wrapOpErr("Switch.Update", err)
	}
	return resp, nil
}
