// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// VPCRouterAPI は VPCRouter リソースに対する操作インターフェース。
type VPCRouterAPI interface {
	ConnectToSwitch(ctx context.Context, zone string, id string, nicIndex string, switchID string) error
	DisconnectFromSwitch(ctx context.Context, zone string, id string, nicIndex string) error
	Logs(ctx context.Context, zone string, id string) (*client.VPCRouterLogsResponseEnvelope, error)
	Ping(ctx context.Context, zone string, id string, destination string) (*client.VPCRouterPingResponseEnvelope, error)
}

var _ VPCRouterAPI = (*vPCRouterOp)(nil)

type vPCRouterOp struct {
	client *client.Client
}

// NewVPCRouterOp は VPCRouterAPI 実装を返す。
func NewVPCRouterOp(c *client.Client) VPCRouterAPI {
	return &vPCRouterOp{client: c}
}

func (op *vPCRouterOp) ConnectToSwitch(ctx context.Context, zone string, id string, nicIndex string, switchID string) error {
	params := client.VPCRouterOpConnectToSwitchParams{Zone: zone, ID: id, NicIndex: nicIndex, SwitchID: switchID}
	_, err := op.client.VPCRouterOpConnectToSwitch(ctx, params)
	if err != nil {
		return wrapOpErr("VPCRouter.ConnectToSwitch", err)
	}
	return nil
}

func (op *vPCRouterOp) DisconnectFromSwitch(ctx context.Context, zone string, id string, nicIndex string) error {
	params := client.VPCRouterOpDisconnectFromSwitchParams{Zone: zone, ID: id, NicIndex: nicIndex}
	_, err := op.client.VPCRouterOpDisconnectFromSwitch(ctx, params)
	if err != nil {
		return wrapOpErr("VPCRouter.DisconnectFromSwitch", err)
	}
	return nil
}

func (op *vPCRouterOp) Logs(ctx context.Context, zone string, id string) (*client.VPCRouterLogsResponseEnvelope, error) {
	params := client.VPCRouterOpLogsParams{Zone: zone, ID: id}
	resp, err := op.client.VPCRouterOpLogs(ctx, params)
	if err != nil {
		return nil, wrapOpErr("VPCRouter.Logs", err)
	}
	return resp, nil
}

func (op *vPCRouterOp) Ping(ctx context.Context, zone string, id string, destination string) (*client.VPCRouterPingResponseEnvelope, error) {
	params := client.VPCRouterOpPingParams{Zone: zone, ID: id, Destination: destination}
	resp, err := op.client.VPCRouterOpPing(ctx, params)
	if err != nil {
		return nil, wrapOpErr("VPCRouter.Ping", err)
	}
	return resp, nil
}
