// Copyright 2022-2026 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-v2-op'; DO NOT EDIT.

package iaas

import (
	"context"

	"github.com/sacloud/iaas-api-go/v2/client"
)

// ZoneAPI は Zone リソースに対する操作インターフェース。
type ZoneAPI interface {
	List(ctx context.Context, zone string, req *client.ZoneFindRequest) (*client.ZoneFindResponseEnvelope, error)
	Read(ctx context.Context, zone string, id string) (*client.ZoneReadResponseEnvelope, error)
}

var _ ZoneAPI = (*zoneOp)(nil)

type zoneOp struct {
	client *client.Client
}

// NewZoneOp は ZoneAPI 実装を返す。
func NewZoneOp(c *client.Client) ZoneAPI {
	return &zoneOp{client: c}
}

func (op *zoneOp) List(ctx context.Context, zone string, req *client.ZoneFindRequest) (*client.ZoneFindResponseEnvelope, error) {
	params := client.ZoneOpFindParams{Zone: zone}
	if req != nil {
		params.Q = req.ToOptString()
	}
	resp, err := op.client.ZoneOpFind(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Zone.List", err)
	}
	return resp, nil
}

func (op *zoneOp) Read(ctx context.Context, zone string, id string) (*client.ZoneReadResponseEnvelope, error) {
	params := client.ZoneOpReadParams{Zone: zone, ID: id}
	resp, err := op.client.ZoneOpRead(ctx, params)
	if err != nil {
		return nil, wrapOpErr("Zone.Read", err)
	}
	return resp, nil
}
