// Copyright 2022-2025 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"sort"
	"strings"
)

type enumMember struct {
	Name  string
	Value string // 文字列または数値リテラル（TypeSpec用）
}

type enumDef struct {
	TypeName string
	Members  []enumMember
}

// generateTypes は types/ パッケージを AST 解析して spec/typespec/types.tsp を生成する。
func generateTypes() {
	typesDir := absPath("types")
	outputPath := absPath("spec/typespec/types.tsp")

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, typesDir, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, 0)
	if err != nil {
		log.Fatalf("failed to parse types dir: %v", err)
	}

	pkg := pkgs["types"]
	if pkg == nil {
		log.Fatal("package 'types' not found")
	}

	// enum ベース型を収集 (型名 → "string" or "int")
	enumBaseTypes := map[string]string{}
	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts := spec.(*ast.TypeSpec)
				ident, ok := ts.Type.(*ast.Ident)
				if !ok {
					continue
				}
				if ident.Name == "string" || ident.Name == "int" {
					enumBaseTypes[ts.Name.Name] = ident.Name
				}
			}
		}
	}

	// var の struct リテラルから enum 値を収集
	enumDefs := map[string]*enumDef{}
	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.VAR {
				continue
			}
			for _, spec := range gd.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok || len(vs.Values) == 0 {
					continue
				}
				// &struct{...} パターン（UnaryExpr）も対応する
				val := vs.Values[0]
				if ue, ok := val.(*ast.UnaryExpr); ok {
					val = ue.X
				}
				cl, ok := val.(*ast.CompositeLit)
				if !ok {
					continue
				}
				st, ok := cl.Type.(*ast.StructType)
				if !ok {
					continue
				}

				// struct フィールドの型から対象の enum 型を特定
				var targetType string
				for _, field := range st.Fields.List {
					ident, ok := field.Type.(*ast.Ident)
					if !ok {
						continue
					}
					if base, ok := enumBaseTypes[ident.Name]; ok {
						targetType = ident.Name
						_ = base
						break
					}
				}
				if targetType == "" {
					continue
				}

				base := enumBaseTypes[targetType]
				def := &enumDef{TypeName: targetType}

				for _, elt := range cl.Elts {
					kv, ok := elt.(*ast.KeyValueExpr)
					if !ok {
						continue
					}
					memberName := kv.Key.(*ast.Ident).Name

					var memberValue string
					switch v := kv.Value.(type) {
					case *ast.CallExpr:
						// EXxx("value") or EXxx(0)
						if len(v.Args) == 1 {
							switch arg := v.Args[0].(type) {
							case *ast.BasicLit:
								if base == "string" {
									memberValue = arg.Value // "value" (クォート付き)
								} else {
									// Go の数値リテラルのアンダースコア区切りを除去 (1_000 → 1000)
									memberValue = strings.ReplaceAll(arg.Value, "_", "")
								}
							case *ast.UnaryExpr:
								// 負の数値 (-1 など)
								lit := strings.ReplaceAll(arg.X.(*ast.BasicLit).Value, "_", "")
								memberValue = fmt.Sprintf("-%s", lit)
							}
						}
					case *ast.BasicLit:
						memberValue = v.Value
					}

					if memberValue == "" {
						continue
					}
					def.Members = append(def.Members, enumMember{Name: memberName, Value: memberValue})
				}

				if len(def.Members) > 0 {
					enumDefs[targetType] = def
				}
			}
		}
	}

	// ソート済みリストを生成
	var sortedDefs []*enumDef
	for _, def := range enumDefs {
		sortedDefs = append(sortedDefs, def)
	}
	sort.Slice(sortedDefs, func(i, j int) bool {
		return sortedDefs[i].TypeName < sortedDefs[j].TypeName
	})

	// enumとして出力する型（固定値のみのホワイトリスト）
	// Goのコードで値が変動しないと確実に言えるもの以外は全てscalarにする
	// 将来APIが新しい値を返してきてもクライアントが破損しないよう、基本的にstring scalarとする
	whitelist := map[string]bool{
		"EDayOfTheWeek": true, // 曜日は固定（これ以外は全て変動ありうる）
	}

	// TypeSpec 出力
	var buf bytes.Buffer
	buf.WriteString("// generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-typespec'; DO NOT EDIT\n\n")
	buf.WriteString("namespace Sacloud.IaaS;\n\n")

	for _, def := range sortedDefs {
		if whitelist[def.TypeName] {
			// ホワイトリスト: enumとして閉じたセットを定義
			buf.WriteString(fmt.Sprintf("enum %s {\n", def.TypeName))
			for i, m := range def.Members {
				comma := ","
				if i == len(def.Members)-1 {
					comma = ""
				}
				memberName := toTypeSpecMemberName(m.Name)
				buf.WriteString(fmt.Sprintf("  %s: %s%s\n", memberName, m.Value, comma))
			}
			buf.WriteString("}\n\n")
		} else {
			// 非ホワイトリスト: scalar extends string（将来の値追加を許容）
			// 既知の値をドキュメントコメントとして記載
			var knownValues []string
			for _, m := range def.Members {
				knownValues = append(knownValues, m.Value)
			}
			buf.WriteString(fmt.Sprintf("/** %s: known values are %s */\n", def.TypeName, strings.Join(knownValues, ", ")))
			buf.WriteString(fmt.Sprintf("scalar %s extends string;\n\n", def.TypeName))
		}
	}

	if err := os.WriteFile(outputPath, buf.Bytes(), 0644); err != nil {
		log.Fatalf("failed to write output: %v", err)
	}
	log.Printf("Writing to: %s (%d enum types)", outputPath, len(sortedDefs))
}

// typespecReserved は TypeSpec の予約語セット（tsp format で失敗するもの）
var typespecReserved = map[string]bool{
	"alias": true, "import": true, "interface": true,
	"model": true, "namespace": true, "op": true, "scalar": true,
	"union": true, "unknown": true, "using": true,
}

// toTypeSpecMemberName は Go のメンバー名を TypeSpec のメンバー名に変換する。
// 予約語はバッククォートでエスケープする。
func toTypeSpecMemberName(name string) string {
	lower := strings.ToLower(name)
	if typespecReserved[lower] {
		return "`" + lower + "`"
	}
	return lower
}
