// Copyright 2022-2025 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/iaas-api-go/internal/tools/gen-find-request'; DO NOT EDIT.

package client

import "encoding/json"

// ArchiveFindFilter は Archive の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type ArchiveFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// Scope は "shared" / "user" のいずれか。部分一致。
	Scope string `json:"Scope,omitempty"`
}

// ArchiveFindRequest は Archive Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type ArchiveFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter ArchiveFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *ArchiveFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *ArchiveFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// AutoBackupFindFilter は AutoBackup の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type AutoBackupFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// ProviderClass は CommonServiceItem の Provider.Class。部分一致。
	ProviderClass string `json:"Provider.Class,omitempty"`
}

// AutoBackupFindRequest は AutoBackup Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type AutoBackupFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter AutoBackupFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *AutoBackupFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *AutoBackupFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// AutoScaleFindFilter は AutoScale の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type AutoScaleFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// ProviderClass は CommonServiceItem の Provider.Class。部分一致。
	ProviderClass string `json:"Provider.Class,omitempty"`
}

// AutoScaleFindRequest は AutoScale Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type AutoScaleFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter AutoScaleFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *AutoScaleFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *AutoScaleFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// BridgeFindFilter は Bridge の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type BridgeFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
}

// BridgeFindRequest は Bridge Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type BridgeFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter BridgeFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *BridgeFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *BridgeFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// CDROMFindFilter は CDROM の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type CDROMFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// Scope は "shared" / "user" のいずれか。部分一致。
	Scope string `json:"Scope,omitempty"`
}

// CDROMFindRequest は CDROM Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type CDROMFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter CDROMFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *CDROMFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *CDROMFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// CertificateAuthorityFindFilter は CertificateAuthority の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type CertificateAuthorityFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// ProviderClass は CommonServiceItem の Provider.Class。部分一致。
	ProviderClass string `json:"Provider.Class,omitempty"`
}

// CertificateAuthorityFindRequest は CertificateAuthority Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type CertificateAuthorityFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter CertificateAuthorityFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *CertificateAuthorityFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *CertificateAuthorityFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// ContainerRegistryFindFilter は ContainerRegistry の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type ContainerRegistryFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// ProviderClass は CommonServiceItem の Provider.Class。部分一致。
	ProviderClass string `json:"Provider.Class,omitempty"`
}

// ContainerRegistryFindRequest は ContainerRegistry Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type ContainerRegistryFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter ContainerRegistryFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *ContainerRegistryFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *ContainerRegistryFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// DNSFindFilter は DNS の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type DNSFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// ProviderClass は CommonServiceItem の Provider.Class。部分一致。
	ProviderClass string `json:"Provider.Class,omitempty"`
}

// DNSFindRequest は DNS Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type DNSFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter DNSFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *DNSFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *DNSFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// DatabaseFindFilter は Database の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type DatabaseFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// Class は Appliance のサブクラス (例: "database"/"loadbalancer")。部分一致。
	Class string `json:"Class,omitempty"`
}

// DatabaseFindRequest は Database Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type DatabaseFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter DatabaseFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *DatabaseFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *DatabaseFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// DiskFindFilter は Disk の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type DiskFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// Scope は "shared" / "user" のいずれか。部分一致。
	Scope string `json:"Scope,omitempty"`
}

// DiskFindRequest は Disk Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type DiskFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter DiskFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *DiskFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *DiskFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// DiskPlanFindFilter は DiskPlan の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type DiskPlanFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
}

// DiskPlanFindRequest は DiskPlan Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type DiskPlanFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter DiskPlanFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *DiskPlanFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *DiskPlanFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// ESMEFindFilter は ESME の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type ESMEFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// ProviderClass は CommonServiceItem の Provider.Class。部分一致。
	ProviderClass string `json:"Provider.Class,omitempty"`
}

// ESMEFindRequest は ESME Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type ESMEFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter ESMEFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *ESMEFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *ESMEFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// EnhancedDBFindFilter は EnhancedDB の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type EnhancedDBFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// ProviderClass は CommonServiceItem の Provider.Class。部分一致。
	ProviderClass string `json:"Provider.Class,omitempty"`
}

// EnhancedDBFindRequest は EnhancedDB Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type EnhancedDBFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter EnhancedDBFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *EnhancedDBFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *EnhancedDBFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// GSLBFindFilter は GSLB の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type GSLBFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// ProviderClass は CommonServiceItem の Provider.Class。部分一致。
	ProviderClass string `json:"Provider.Class,omitempty"`
}

// GSLBFindRequest は GSLB Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type GSLBFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter GSLBFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *GSLBFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *GSLBFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// IconFindFilter は Icon の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type IconFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// Scope は "shared" / "user" のいずれか。部分一致。
	Scope string `json:"Scope,omitempty"`
}

// IconFindRequest は Icon Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type IconFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter IconFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *IconFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *IconFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// InterfaceFindFilter は Interface の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type InterfaceFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
}

// InterfaceFindRequest は Interface Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type InterfaceFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter InterfaceFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *InterfaceFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *InterfaceFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// InternetFindFilter は Internet の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type InternetFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
}

// InternetFindRequest は Internet Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type InternetFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter InternetFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *InternetFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *InternetFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// InternetPlanFindFilter は InternetPlan の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type InternetPlanFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
}

// InternetPlanFindRequest は InternetPlan Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type InternetPlanFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter InternetPlanFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *InternetPlanFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *InternetPlanFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// LicenseFindFilter は License の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type LicenseFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
}

// LicenseFindRequest は License Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type LicenseFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter LicenseFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *LicenseFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *LicenseFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// LicenseInfoFindFilter は LicenseInfo の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type LicenseInfoFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
}

// LicenseInfoFindRequest は LicenseInfo Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type LicenseInfoFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter LicenseInfoFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *LicenseInfoFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *LicenseInfoFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// LoadBalancerFindFilter は LoadBalancer の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type LoadBalancerFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// Class は Appliance のサブクラス (例: "database"/"loadbalancer")。部分一致。
	Class string `json:"Class,omitempty"`
}

// LoadBalancerFindRequest は LoadBalancer Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type LoadBalancerFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter LoadBalancerFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *LoadBalancerFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *LoadBalancerFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// LocalRouterFindFilter は LocalRouter の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type LocalRouterFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// ProviderClass は CommonServiceItem の Provider.Class。部分一致。
	ProviderClass string `json:"Provider.Class,omitempty"`
}

// LocalRouterFindRequest は LocalRouter Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type LocalRouterFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter LocalRouterFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *LocalRouterFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *LocalRouterFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// MobileGatewayFindFilter は MobileGateway の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type MobileGatewayFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// Class は Appliance のサブクラス (例: "database"/"loadbalancer")。部分一致。
	Class string `json:"Class,omitempty"`
}

// MobileGatewayFindRequest は MobileGateway Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type MobileGatewayFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter MobileGatewayFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *MobileGatewayFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *MobileGatewayFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// NFSFindFilter は NFS の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type NFSFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// Class は Appliance のサブクラス (例: "database"/"loadbalancer")。部分一致。
	Class string `json:"Class,omitempty"`
}

// NFSFindRequest は NFS Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type NFSFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter NFSFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *NFSFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *NFSFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// NoteFindFilter は Note の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type NoteFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// Scope は "shared" / "user" のいずれか。部分一致。
	Scope string `json:"Scope,omitempty"`
}

// NoteFindRequest は Note Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type NoteFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter NoteFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *NoteFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *NoteFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// PacketFilterFindFilter は PacketFilter の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type PacketFilterFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
}

// PacketFilterFindRequest は PacketFilter Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type PacketFilterFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter PacketFilterFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *PacketFilterFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *PacketFilterFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// PrivateHostFindFilter は PrivateHost の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type PrivateHostFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
}

// PrivateHostFindRequest は PrivateHost Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type PrivateHostFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter PrivateHostFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *PrivateHostFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *PrivateHostFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// PrivateHostPlanFindFilter は PrivateHostPlan の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type PrivateHostPlanFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Class は Appliance のサブクラス (例: "database"/"loadbalancer")。部分一致。
	Class string `json:"Class,omitempty"`
}

// PrivateHostPlanFindRequest は PrivateHostPlan Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type PrivateHostPlanFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter PrivateHostPlanFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *PrivateHostPlanFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *PrivateHostPlanFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// ProxyLBFindFilter は ProxyLB の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type ProxyLBFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// ProviderClass は CommonServiceItem の Provider.Class。部分一致。
	ProviderClass string `json:"Provider.Class,omitempty"`
}

// ProxyLBFindRequest は ProxyLB Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type ProxyLBFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter ProxyLBFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *ProxyLBFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *ProxyLBFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// RegionFindFilter は Region の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type RegionFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
}

// RegionFindRequest は Region Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type RegionFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter RegionFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *RegionFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *RegionFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// SIMFindFilter は SIM の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type SIMFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// ProviderClass は CommonServiceItem の Provider.Class。部分一致。
	ProviderClass string `json:"Provider.Class,omitempty"`
}

// SIMFindRequest は SIM Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type SIMFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter SIMFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *SIMFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *SIMFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// SSHKeyFindFilter は SSHKey の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type SSHKeyFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
}

// SSHKeyFindRequest は SSHKey Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type SSHKeyFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter SSHKeyFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *SSHKeyFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *SSHKeyFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// ServerFindFilter は Server の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type ServerFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
}

// ServerFindRequest は Server Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type ServerFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter ServerFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *ServerFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *ServerFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// ServerPlanFindFilter は ServerPlan の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type ServerPlanFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
}

// ServerPlanFindRequest は ServerPlan Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type ServerPlanFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter ServerPlanFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *ServerPlanFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *ServerPlanFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// ServiceClassFindFilter は ServiceClass の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type ServiceClassFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
}

// ServiceClassFindRequest は ServiceClass Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type ServiceClassFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter ServiceClassFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *ServiceClassFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *ServiceClassFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// SimpleMonitorFindFilter は SimpleMonitor の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type SimpleMonitorFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// ProviderClass は CommonServiceItem の Provider.Class。部分一致。
	ProviderClass string `json:"Provider.Class,omitempty"`
}

// SimpleMonitorFindRequest は SimpleMonitor Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type SimpleMonitorFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter SimpleMonitorFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *SimpleMonitorFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *SimpleMonitorFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// SimpleNotificationDestinationFindFilter は SimpleNotificationDestination の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type SimpleNotificationDestinationFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// ProviderClass は CommonServiceItem の Provider.Class。部分一致。
	ProviderClass string `json:"Provider.Class,omitempty"`
}

// SimpleNotificationDestinationFindRequest は SimpleNotificationDestination Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type SimpleNotificationDestinationFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter SimpleNotificationDestinationFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *SimpleNotificationDestinationFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *SimpleNotificationDestinationFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// SimpleNotificationGroupFindFilter は SimpleNotificationGroup の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type SimpleNotificationGroupFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// ProviderClass は CommonServiceItem の Provider.Class。部分一致。
	ProviderClass string `json:"Provider.Class,omitempty"`
}

// SimpleNotificationGroupFindRequest は SimpleNotificationGroup Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type SimpleNotificationGroupFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter SimpleNotificationGroupFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *SimpleNotificationGroupFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *SimpleNotificationGroupFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// SubnetFindFilter は Subnet の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type SubnetFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
}

// SubnetFindRequest は Subnet Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type SubnetFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter SubnetFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *SubnetFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *SubnetFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// SwitchFindFilter は Switch の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type SwitchFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// Scope は "shared" / "user" のいずれか。部分一致。
	Scope string `json:"Scope,omitempty"`
}

// SwitchFindRequest は Switch Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type SwitchFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter SwitchFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *SwitchFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *SwitchFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// VPCRouterFindFilter は VPCRouter の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type VPCRouterFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
	// Tags はタグ配列の完全一致 AND 検索。
	Tags []string `json:"Tags,omitempty"`
	// Class は Appliance のサブクラス (例: "database"/"loadbalancer")。部分一致。
	Class string `json:"Class,omitempty"`
}

// VPCRouterFindRequest は VPCRouter Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type VPCRouterFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter VPCRouterFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *VPCRouterFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *VPCRouterFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}

// ZoneFindFilter は Zone の Find クエリで指定可能なフィルタ条件。
// 省略されたフィールド (zero value) は q= に含まれない。
type ZoneFindFilter struct {
	// Name は部分一致検索（スペース区切りで AND 結合）。
	Name string `json:"Name,omitempty"`
}

// ZoneFindRequest は Zone Find エンドポイント用の q= クエリ値。
// ToOptString() で OptString に変換して Params.Q に渡す。
type ZoneFindRequest struct {
	// Count は取得件数の上限 (0 はサーバーデフォルト)。
	Count int32 `json:"Count,omitempty"`
	// From はページング開始オフセット。
	From int32 `json:"From,omitempty"`
	// Filter はフィルタ条件。未指定の場合は q 全体から省略される。
	Filter ZoneFindFilter `json:"Filter,omitempty"`
}

// Marshal は JSON エンコード後の文字列を返す。エラーは起こらない想定。
func (r *ZoneFindRequest) Marshal() string {
	b, err := json.Marshal(r)
	if err != nil {
		return "{}"
	}
	return string(b)
}

// ToOptString は Marshal 結果を OptString にラップする。
// q クエリパラメータ (Params.Q) への代入用。
func (r *ZoneFindRequest) ToOptString() OptString {
	return NewOptString(r.Marshal())
}
