// Code generated by ogen, DO NOT EDIT.

package client

// ApplianceOpBootParams is parameters of ApplianceOp_boot operation.
type ApplianceOpBootParams struct {
	Zone string
	ID   string
}

// ApplianceOpConfigParams is parameters of ApplianceOp_config operation.
type ApplianceOpConfigParams struct {
	Zone string
	ID   string
}

// ApplianceOpCreateParams is parameters of ApplianceOp_create operation.
type ApplianceOpCreateParams struct {
	Zone string
}

// ApplianceOpDeleteParams is parameters of ApplianceOp_delete operation.
type ApplianceOpDeleteParams struct {
	Zone string
	ID   string
}

// ApplianceOpFindParams is parameters of ApplianceOp_find operation.
type ApplianceOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合
	// - `Tags` (string[]): タグ完全一致の AND 結合
	// - `Class` (string): Appliance のサブクラス（例 `database` /
	// `loadbalancer`）の部分一致.
	Q OptString `json:",omitempty,omitzero"`
}

// ApplianceOpMonitorCPUParams is parameters of ApplianceOp_monitorCPU operation.
type ApplianceOpMonitorCPUParams struct {
	Zone string
	ID   string
}

// ApplianceOpMonitorDatabaseParams is parameters of ApplianceOp_monitorDatabase operation.
type ApplianceOpMonitorDatabaseParams struct {
	Zone string
	ID   string
}

// ApplianceOpMonitorInterfaceParams is parameters of ApplianceOp_monitorInterface operation.
type ApplianceOpMonitorInterfaceParams struct {
	Zone string
	ID   string
}

// ApplianceOpMonitorInterfaceByIndexParams is parameters of ApplianceOp_monitorInterfaceByIndex operation.
type ApplianceOpMonitorInterfaceByIndexParams struct {
	Zone  string
	ID    string
	Index string
}

// ApplianceOpReadParams is parameters of ApplianceOp_read operation.
type ApplianceOpReadParams struct {
	Zone string
	ID   string
}

// ApplianceOpResetParams is parameters of ApplianceOp_reset operation.
type ApplianceOpResetParams struct {
	Zone string
	ID   string
}

// ApplianceOpShutdownParams is parameters of ApplianceOp_shutdown operation.
type ApplianceOpShutdownParams struct {
	Zone string
	ID   string
}

// ApplianceOpStatusParams is parameters of ApplianceOp_status operation.
type ApplianceOpStatusParams struct {
	Zone string
	ID   string
}

// ApplianceOpUpdateParams is parameters of ApplianceOp_update operation.
type ApplianceOpUpdateParams struct {
	Zone string
	ID   string
}

// ArchiveOpCloseFTPParams is parameters of ArchiveOp_closeFTP operation.
type ArchiveOpCloseFTPParams struct {
	Zone string
	ID   string
}

// ArchiveOpCreateParams is parameters of ArchiveOp_create operation.
type ArchiveOpCreateParams struct {
	Zone string
}

// ArchiveOpDeleteParams is parameters of ArchiveOp_delete operation.
type ArchiveOpDeleteParams struct {
	Zone string
	ID   string
}

// ArchiveOpFindParams is parameters of ArchiveOp_find operation.
type ArchiveOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合
	// - `Tags` (string[]): タグ完全一致の AND 結合
	// - `Scope` (string): `"shared"` または `"user"` の部分一致.
	Q OptString `json:",omitempty,omitzero"`
}

// ArchiveOpReadParams is parameters of ArchiveOp_read operation.
type ArchiveOpReadParams struct {
	Zone string
	ID   string
}

// ArchiveOpShareParams is parameters of ArchiveOp_share operation.
type ArchiveOpShareParams struct {
	Zone string
	ID   string
}

// ArchiveOpTransferParams is parameters of ArchiveOp_transfer operation.
type ArchiveOpTransferParams struct {
	Zone            string
	SourceArchiveID string
	DestZoneID      string
}

// ArchiveOpUpdateParams is parameters of ArchiveOp_update operation.
type ArchiveOpUpdateParams struct {
	Zone string
	ID   string
}

// AuthStatusOpReadParams is parameters of AuthStatusOp_read operation.
type AuthStatusOpReadParams struct {
	Zone string
}

// AutoScaleOpScaleDownParams is parameters of AutoScaleOp_scaleDown operation.
type AutoScaleOpScaleDownParams struct {
	Zone string
	ID   string
}

// AutoScaleOpScaleUpParams is parameters of AutoScaleOp_scaleUp operation.
type AutoScaleOpScaleUpParams struct {
	Zone string
	ID   string
}

// AutoScaleOpStatusParams is parameters of AutoScaleOp_status operation.
type AutoScaleOpStatusParams struct {
	Zone string
	ID   string
}

// BillOpByContractParams is parameters of BillOp_byContract operation.
type BillOpByContractParams struct {
	Zone      string
	AccountID string
}

// BillOpByContractYearParams is parameters of BillOp_byContractYear operation.
type BillOpByContractYearParams struct {
	Zone      string
	AccountID string
	Year      string
}

// BillOpByContractYearMonthParams is parameters of BillOp_byContractYearMonth operation.
type BillOpByContractYearMonthParams struct {
	Zone      string
	AccountID string
	Year      string
	Month     string
}

// BillOpDetailsParams is parameters of BillOp_details operation.
type BillOpDetailsParams struct {
	Zone       string
	MemberCode string
	ID         string
}

// BillOpDetailsCSVParams is parameters of BillOp_detailsCSV operation.
type BillOpDetailsCSVParams struct {
	Zone       string
	MemberCode string
	ID         string
}

// BillOpReadParams is parameters of BillOp_read operation.
type BillOpReadParams struct {
	Zone string
	ID   string
}

// BridgeOpCreateParams is parameters of BridgeOp_create operation.
type BridgeOpCreateParams struct {
	Zone string
}

// BridgeOpDeleteParams is parameters of BridgeOp_delete operation.
type BridgeOpDeleteParams struct {
	Zone string
	ID   string
}

// BridgeOpFindParams is parameters of BridgeOp_find operation.
type BridgeOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合.
	Q OptString `json:",omitempty,omitzero"`
}

// BridgeOpReadParams is parameters of BridgeOp_read operation.
type BridgeOpReadParams struct {
	Zone string
	ID   string
}

// BridgeOpUpdateParams is parameters of BridgeOp_update operation.
type BridgeOpUpdateParams struct {
	Zone string
	ID   string
}

// CDROMOpCloseFTPParams is parameters of CDROMOp_closeFTP operation.
type CDROMOpCloseFTPParams struct {
	Zone string
	ID   string
}

// CDROMOpCreateParams is parameters of CDROMOp_create operation.
type CDROMOpCreateParams struct {
	Zone string
}

// CDROMOpDeleteParams is parameters of CDROMOp_delete operation.
type CDROMOpDeleteParams struct {
	Zone string
	ID   string
}

// CDROMOpFindParams is parameters of CDROMOp_find operation.
type CDROMOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合
	// - `Tags` (string[]): タグ完全一致の AND 結合
	// - `Scope` (string): `"shared"` または `"user"` の部分一致.
	Q OptString `json:",omitempty,omitzero"`
}

// CDROMOpOpenFTPParams is parameters of CDROMOp_openFTP operation.
type CDROMOpOpenFTPParams struct {
	Zone string
	ID   string
}

// CDROMOpReadParams is parameters of CDROMOp_read operation.
type CDROMOpReadParams struct {
	Zone string
	ID   string
}

// CDROMOpUpdateParams is parameters of CDROMOp_update operation.
type CDROMOpUpdateParams struct {
	Zone string
	ID   string
}

// CertificateAuthorityOpAddClientParams is parameters of CertificateAuthorityOp_addClient operation.
type CertificateAuthorityOpAddClientParams struct {
	Zone string
	ID   string
}

// CertificateAuthorityOpAddServerParams is parameters of CertificateAuthorityOp_addServer operation.
type CertificateAuthorityOpAddServerParams struct {
	Zone string
	ID   string
}

// CertificateAuthorityOpDenyClientParams is parameters of CertificateAuthorityOp_denyClient operation.
type CertificateAuthorityOpDenyClientParams struct {
	Zone     string
	ID       string
	ClientID string
}

// CertificateAuthorityOpDetailParams is parameters of CertificateAuthorityOp_detail operation.
type CertificateAuthorityOpDetailParams struct {
	Zone string
	ID   string
}

// CertificateAuthorityOpHoldClientParams is parameters of CertificateAuthorityOp_holdClient operation.
type CertificateAuthorityOpHoldClientParams struct {
	Zone     string
	ID       string
	ClientID string
}

// CertificateAuthorityOpHoldServerParams is parameters of CertificateAuthorityOp_holdServer operation.
type CertificateAuthorityOpHoldServerParams struct {
	Zone     string
	ID       string
	ServerID string
}

// CertificateAuthorityOpListClientsParams is parameters of CertificateAuthorityOp_listClients operation.
type CertificateAuthorityOpListClientsParams struct {
	Zone string
	ID   string
}

// CertificateAuthorityOpListServersParams is parameters of CertificateAuthorityOp_listServers operation.
type CertificateAuthorityOpListServersParams struct {
	Zone string
	ID   string
}

// CertificateAuthorityOpReadClientParams is parameters of CertificateAuthorityOp_readClient operation.
type CertificateAuthorityOpReadClientParams struct {
	Zone     string
	ID       string
	ClientID string
}

// CertificateAuthorityOpReadServerParams is parameters of CertificateAuthorityOp_readServer operation.
type CertificateAuthorityOpReadServerParams struct {
	Zone     string
	ID       string
	ServerID string
}

// CertificateAuthorityOpResumeClientParams is parameters of CertificateAuthorityOp_resumeClient operation.
type CertificateAuthorityOpResumeClientParams struct {
	Zone     string
	ID       string
	ClientID string
}

// CertificateAuthorityOpResumeServerParams is parameters of CertificateAuthorityOp_resumeServer operation.
type CertificateAuthorityOpResumeServerParams struct {
	Zone     string
	ID       string
	ServerID string
}

// CertificateAuthorityOpRevokeClientParams is parameters of CertificateAuthorityOp_revokeClient operation.
type CertificateAuthorityOpRevokeClientParams struct {
	Zone     string
	ID       string
	ClientID string
}

// CertificateAuthorityOpRevokeServerParams is parameters of CertificateAuthorityOp_revokeServer operation.
type CertificateAuthorityOpRevokeServerParams struct {
	Zone     string
	ID       string
	ServerID string
}

// CommonServiceItemOpCreateParams is parameters of CommonServiceItemOp_create operation.
type CommonServiceItemOpCreateParams struct {
	Zone string
}

// CommonServiceItemOpDeleteParams is parameters of CommonServiceItemOp_delete operation.
type CommonServiceItemOpDeleteParams struct {
	Zone string
	ID   string
}

// CommonServiceItemOpFindParams is parameters of CommonServiceItemOp_find operation.
type CommonServiceItemOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合
	// - `Tags` (string[]): タグ完全一致の AND 結合
	// - `Provider.Class` (string): CommonServiceItem のプロバイダ種別の部分一致.
	Q OptString `json:",omitempty,omitzero"`
}

// CommonServiceItemOpHealthStatusParams is parameters of CommonServiceItemOp_healthStatus operation.
type CommonServiceItemOpHealthStatusParams struct {
	Zone string
	ID   string
}

// CommonServiceItemOpReadParams is parameters of CommonServiceItemOp_read operation.
type CommonServiceItemOpReadParams struct {
	Zone string
	ID   string
}

// CommonServiceItemOpUpdateParams is parameters of CommonServiceItemOp_update operation.
type CommonServiceItemOpUpdateParams struct {
	Zone string
	ID   string
}

// ContainerRegistryOpAddUserParams is parameters of ContainerRegistryOp_addUser operation.
type ContainerRegistryOpAddUserParams struct {
	Zone string
	ID   string
}

// ContainerRegistryOpDeleteUserParams is parameters of ContainerRegistryOp_deleteUser operation.
type ContainerRegistryOpDeleteUserParams struct {
	Zone     string
	ID       string
	Username string
}

// ContainerRegistryOpListUsersParams is parameters of ContainerRegistryOp_listUsers operation.
type ContainerRegistryOpListUsersParams struct {
	Zone string
	ID   string
}

// ContainerRegistryOpUpdateUserParams is parameters of ContainerRegistryOp_updateUser operation.
type ContainerRegistryOpUpdateUserParams struct {
	Zone     string
	ID       string
	Username string
}

// CouponOpFindParams is parameters of CouponOp_find operation.
type CouponOpFindParams struct {
	Zone      string
	AccountID string
}

// DatabaseOpGetParameterParams is parameters of DatabaseOp_getParameter operation.
type DatabaseOpGetParameterParams struct {
	Zone string
	ID   string
}

// DatabaseOpMonitorDiskParams is parameters of DatabaseOp_monitorDisk operation.
type DatabaseOpMonitorDiskParams struct {
	Zone string
	ID   string
}

// DatabaseOpSetParameterParams is parameters of DatabaseOp_setParameter operation.
type DatabaseOpSetParameterParams struct {
	Zone string
	ID   string
}

// DiskOpConfigParams is parameters of DiskOp_config operation.
type DiskOpConfigParams struct {
	Zone string
	ID   string
}

// DiskOpConnectToServerParams is parameters of DiskOp_connectToServer operation.
type DiskOpConnectToServerParams struct {
	Zone     string
	ID       string
	ServerID string
}

// DiskOpCreateParams is parameters of DiskOp_create operation.
type DiskOpCreateParams struct {
	Zone string
}

// DiskOpDeleteParams is parameters of DiskOp_delete operation.
type DiskOpDeleteParams struct {
	Zone string
	ID   string
}

// DiskOpDisconnectFromServerParams is parameters of DiskOp_disconnectFromServer operation.
type DiskOpDisconnectFromServerParams struct {
	Zone string
	ID   string
}

// DiskOpFindParams is parameters of DiskOp_find operation.
type DiskOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合
	// - `Tags` (string[]): タグ完全一致の AND 結合
	// - `Scope` (string): `"shared"` または `"user"` の部分一致.
	Q OptString `json:",omitempty,omitzero"`
}

// DiskOpMonitorParams is parameters of DiskOp_monitor operation.
type DiskOpMonitorParams struct {
	Zone string
	ID   string
}

// DiskOpReadParams is parameters of DiskOp_read operation.
type DiskOpReadParams struct {
	Zone string
	ID   string
}

// DiskOpResizePartitionParams is parameters of DiskOp_resizePartition operation.
type DiskOpResizePartitionParams struct {
	Zone string
	ID   string
}

// DiskOpUpdateParams is parameters of DiskOp_update operation.
type DiskOpUpdateParams struct {
	Zone string
	ID   string
}

// DiskPlanOpFindParams is parameters of DiskPlanOp_find operation.
type DiskPlanOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合.
	Q OptString `json:",omitempty,omitzero"`
}

// DiskPlanOpReadParams is parameters of DiskPlanOp_read operation.
type DiskPlanOpReadParams struct {
	Zone string
	ID   string
}

// ESMEOpLogsParams is parameters of ESMEOp_logs operation.
type ESMEOpLogsParams struct {
	Zone string
	ID   string
}

// ESMEOpSendMessageWithGeneratedOTPParams is parameters of ESMEOp_sendMessageWithGeneratedOTP operation.
type ESMEOpSendMessageWithGeneratedOTPParams struct {
	Zone string
	ID   string
}

// ESMEOpSendMessageWithInputtedOTPParams is parameters of ESMEOp_sendMessageWithInputtedOTP operation.
type ESMEOpSendMessageWithInputtedOTPParams struct {
	Zone string
	ID   string
}

// EnhancedDBOpGetConfigParams is parameters of EnhancedDBOp_getConfig operation.
type EnhancedDBOpGetConfigParams struct {
	Zone string
	ID   string
}

// EnhancedDBOpSetConfigParams is parameters of EnhancedDBOp_setConfig operation.
type EnhancedDBOpSetConfigParams struct {
	Zone string
	ID   string
}

// EnhancedDBOpSetPasswordParams is parameters of EnhancedDBOp_setPassword operation.
type EnhancedDBOpSetPasswordParams struct {
	Zone string
	ID   string
}

// IPAddressOpListParams is parameters of IPAddressOp_list operation.
type IPAddressOpListParams struct {
	Zone string
}

// IPAddressOpReadParams is parameters of IPAddressOp_read operation.
type IPAddressOpReadParams struct {
	Zone      string
	IpAddress string
}

// IPAddressOpUpdateHostNameParams is parameters of IPAddressOp_updateHostName operation.
type IPAddressOpUpdateHostNameParams struct {
	Zone      string
	IpAddress string
}

// IPv6AddrOpCreateParams is parameters of IPv6AddrOp_create operation.
type IPv6AddrOpCreateParams struct {
	Zone string
}

// IPv6AddrOpDeleteParams is parameters of IPv6AddrOp_delete operation.
type IPv6AddrOpDeleteParams struct {
	Zone string
	ID   string
}

// IPv6AddrOpFindParams is parameters of IPv6AddrOp_find operation.
type IPv6AddrOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット.
	Q OptString `json:",omitempty,omitzero"`
}

// IPv6AddrOpReadParams is parameters of IPv6AddrOp_read operation.
type IPv6AddrOpReadParams struct {
	Zone string
	ID   string
}

// IPv6AddrOpUpdateParams is parameters of IPv6AddrOp_update operation.
type IPv6AddrOpUpdateParams struct {
	Zone string
	ID   string
}

// IPv6NetOpListParams is parameters of IPv6NetOp_list operation.
type IPv6NetOpListParams struct {
	Zone string
}

// IPv6NetOpReadParams is parameters of IPv6NetOp_read operation.
type IPv6NetOpReadParams struct {
	Zone string
	ID   string
}

// IconOpCreateParams is parameters of IconOp_create operation.
type IconOpCreateParams struct {
	Zone string
}

// IconOpDeleteParams is parameters of IconOp_delete operation.
type IconOpDeleteParams struct {
	Zone string
	ID   string
}

// IconOpFindParams is parameters of IconOp_find operation.
type IconOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合
	// - `Tags` (string[]): タグ完全一致の AND 結合
	// - `Scope` (string): `"shared"` または `"user"` の部分一致.
	Q OptString `json:",omitempty,omitzero"`
}

// IconOpReadParams is parameters of IconOp_read operation.
type IconOpReadParams struct {
	Zone string
	ID   string
}

// IconOpUpdateParams is parameters of IconOp_update operation.
type IconOpUpdateParams struct {
	Zone string
	ID   string
}

// InterfaceOpConnectToPacketFilterParams is parameters of InterfaceOp_connectToPacketFilter operation.
type InterfaceOpConnectToPacketFilterParams struct {
	Zone           string
	ID             string
	PacketFilterID string
}

// InterfaceOpConnectToSharedSegmentParams is parameters of InterfaceOp_connectToSharedSegment operation.
type InterfaceOpConnectToSharedSegmentParams struct {
	Zone string
	ID   string
}

// InterfaceOpConnectToSwitchParams is parameters of InterfaceOp_connectToSwitch operation.
type InterfaceOpConnectToSwitchParams struct {
	Zone     string
	ID       string
	SwitchID string
}

// InterfaceOpCreateParams is parameters of InterfaceOp_create operation.
type InterfaceOpCreateParams struct {
	Zone string
}

// InterfaceOpDeleteParams is parameters of InterfaceOp_delete operation.
type InterfaceOpDeleteParams struct {
	Zone string
	ID   string
}

// InterfaceOpDisconnectFromPacketFilterParams is parameters of InterfaceOp_disconnectFromPacketFilter operation.
type InterfaceOpDisconnectFromPacketFilterParams struct {
	Zone string
	ID   string
}

// InterfaceOpDisconnectFromSwitchParams is parameters of InterfaceOp_disconnectFromSwitch operation.
type InterfaceOpDisconnectFromSwitchParams struct {
	Zone string
	ID   string
}

// InterfaceOpFindParams is parameters of InterfaceOp_find operation.
type InterfaceOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合.
	Q OptString `json:",omitempty,omitzero"`
}

// InterfaceOpMonitorParams is parameters of InterfaceOp_monitor operation.
type InterfaceOpMonitorParams struct {
	Zone string
	ID   string
}

// InterfaceOpReadParams is parameters of InterfaceOp_read operation.
type InterfaceOpReadParams struct {
	Zone string
	ID   string
}

// InterfaceOpUpdateParams is parameters of InterfaceOp_update operation.
type InterfaceOpUpdateParams struct {
	Zone string
	ID   string
}

// InternetOpAddSubnetParams is parameters of InternetOp_addSubnet operation.
type InternetOpAddSubnetParams struct {
	Zone string
	ID   string
}

// InternetOpCreateParams is parameters of InternetOp_create operation.
type InternetOpCreateParams struct {
	Zone string
}

// InternetOpDeleteParams is parameters of InternetOp_delete operation.
type InternetOpDeleteParams struct {
	Zone string
	ID   string
}

// InternetOpDeleteSubnetParams is parameters of InternetOp_deleteSubnet operation.
type InternetOpDeleteSubnetParams struct {
	Zone     string
	ID       string
	SubnetID string
}

// InternetOpDisableIPv6Params is parameters of InternetOp_disableIPv6 operation.
type InternetOpDisableIPv6Params struct {
	Zone      string
	ID        string
	Ipv6netID string
}

// InternetOpEnableIPv6Params is parameters of InternetOp_enableIPv6 operation.
type InternetOpEnableIPv6Params struct {
	Zone string
	ID   string
}

// InternetOpFindParams is parameters of InternetOp_find operation.
type InternetOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合
	// - `Tags` (string[]): タグ完全一致の AND 結合.
	Q OptString `json:",omitempty,omitzero"`
}

// InternetOpMonitorParams is parameters of InternetOp_monitor operation.
type InternetOpMonitorParams struct {
	Zone string
	ID   string
}

// InternetOpReadParams is parameters of InternetOp_read operation.
type InternetOpReadParams struct {
	Zone string
	ID   string
}

// InternetOpUpdateParams is parameters of InternetOp_update operation.
type InternetOpUpdateParams struct {
	Zone string
	ID   string
}

// InternetOpUpdateBandWidthParams is parameters of InternetOp_updateBandWidth operation.
type InternetOpUpdateBandWidthParams struct {
	Zone string
	ID   string
}

// InternetOpUpdateSubnetParams is parameters of InternetOp_updateSubnet operation.
type InternetOpUpdateSubnetParams struct {
	Zone     string
	ID       string
	SubnetID string
}

// InternetPlanOpFindParams is parameters of InternetPlanOp_find operation.
type InternetPlanOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合.
	Q OptString `json:",omitempty,omitzero"`
}

// InternetPlanOpReadParams is parameters of InternetPlanOp_read operation.
type InternetPlanOpReadParams struct {
	Zone string
	ID   string
}

// LicenseInfoOpFindParams is parameters of LicenseInfoOp_find operation.
type LicenseInfoOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合.
	Q OptString `json:",omitempty,omitzero"`
}

// LicenseInfoOpReadParams is parameters of LicenseInfoOp_read operation.
type LicenseInfoOpReadParams struct {
	Zone string
	ID   string
}

// LicenseOpCreateParams is parameters of LicenseOp_create operation.
type LicenseOpCreateParams struct {
	Zone string
}

// LicenseOpDeleteParams is parameters of LicenseOp_delete operation.
type LicenseOpDeleteParams struct {
	Zone string
	ID   string
}

// LicenseOpFindParams is parameters of LicenseOp_find operation.
type LicenseOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合.
	Q OptString `json:",omitempty,omitzero"`
}

// LicenseOpReadParams is parameters of LicenseOp_read operation.
type LicenseOpReadParams struct {
	Zone string
	ID   string
}

// LicenseOpUpdateParams is parameters of LicenseOp_update operation.
type LicenseOpUpdateParams struct {
	Zone string
	ID   string
}

// LocalRouterOpMonitorLocalRouterParams is parameters of LocalRouterOp_monitorLocalRouter operation.
type LocalRouterOpMonitorLocalRouterParams struct {
	Zone string
	ID   string
}

// MobileGatewayOpAddSIMParams is parameters of MobileGatewayOp_addSIM operation.
type MobileGatewayOpAddSIMParams struct {
	Zone string
	ID   string
}

// MobileGatewayOpConnectToSwitchParams is parameters of MobileGatewayOp_connectToSwitch operation.
type MobileGatewayOpConnectToSwitchParams struct {
	Zone     string
	ID       string
	SwitchID string
}

// MobileGatewayOpDeleteSIMParams is parameters of MobileGatewayOp_deleteSIM operation.
type MobileGatewayOpDeleteSIMParams struct {
	Zone  string
	ID    string
	SimID string
}

// MobileGatewayOpDeleteTrafficConfigParams is parameters of MobileGatewayOp_deleteTrafficConfig operation.
type MobileGatewayOpDeleteTrafficConfigParams struct {
	Zone string
	ID   string
}

// MobileGatewayOpDisconnectFromSwitchParams is parameters of MobileGatewayOp_disconnectFromSwitch operation.
type MobileGatewayOpDisconnectFromSwitchParams struct {
	Zone string
	ID   string
}

// MobileGatewayOpGetDNSParams is parameters of MobileGatewayOp_getDNS operation.
type MobileGatewayOpGetDNSParams struct {
	Zone string
	ID   string
}

// MobileGatewayOpGetSIMRoutesParams is parameters of MobileGatewayOp_getSIMRoutes operation.
type MobileGatewayOpGetSIMRoutesParams struct {
	Zone string
	ID   string
}

// MobileGatewayOpGetTrafficConfigParams is parameters of MobileGatewayOp_getTrafficConfig operation.
type MobileGatewayOpGetTrafficConfigParams struct {
	Zone string
	ID   string
}

// MobileGatewayOpListSIMParams is parameters of MobileGatewayOp_listSIM operation.
type MobileGatewayOpListSIMParams struct {
	Zone string
	ID   string
}

// MobileGatewayOpLogsParams is parameters of MobileGatewayOp_logs operation.
type MobileGatewayOpLogsParams struct {
	Zone string
	ID   string
}

// MobileGatewayOpSetDNSParams is parameters of MobileGatewayOp_setDNS operation.
type MobileGatewayOpSetDNSParams struct {
	Zone string
	ID   string
}

// MobileGatewayOpSetSIMRoutesParams is parameters of MobileGatewayOp_setSIMRoutes operation.
type MobileGatewayOpSetSIMRoutesParams struct {
	Zone string
	ID   string
}

// MobileGatewayOpSetTrafficConfigParams is parameters of MobileGatewayOp_setTrafficConfig operation.
type MobileGatewayOpSetTrafficConfigParams struct {
	Zone string
	ID   string
}

// MobileGatewayOpTrafficStatusParams is parameters of MobileGatewayOp_trafficStatus operation.
type MobileGatewayOpTrafficStatusParams struct {
	Zone string
	ID   string
}

// NoteOpCreateParams is parameters of NoteOp_create operation.
type NoteOpCreateParams struct {
	Zone string
}

// NoteOpDeleteParams is parameters of NoteOp_delete operation.
type NoteOpDeleteParams struct {
	Zone string
	ID   string
}

// NoteOpFindParams is parameters of NoteOp_find operation.
type NoteOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合
	// - `Tags` (string[]): タグ完全一致の AND 結合
	// - `Scope` (string): `"shared"` または `"user"` の部分一致.
	Q OptString `json:",omitempty,omitzero"`
}

// NoteOpReadParams is parameters of NoteOp_read operation.
type NoteOpReadParams struct {
	Zone string
	ID   string
}

// NoteOpUpdateParams is parameters of NoteOp_update operation.
type NoteOpUpdateParams struct {
	Zone string
	ID   string
}

// PacketFilterOpCreateParams is parameters of PacketFilterOp_create operation.
type PacketFilterOpCreateParams struct {
	Zone string
}

// PacketFilterOpDeleteParams is parameters of PacketFilterOp_delete operation.
type PacketFilterOpDeleteParams struct {
	Zone string
	ID   string
}

// PacketFilterOpFindParams is parameters of PacketFilterOp_find operation.
type PacketFilterOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合.
	Q OptString `json:",omitempty,omitzero"`
}

// PacketFilterOpReadParams is parameters of PacketFilterOp_read operation.
type PacketFilterOpReadParams struct {
	Zone string
	ID   string
}

// PacketFilterOpUpdateParams is parameters of PacketFilterOp_update operation.
type PacketFilterOpUpdateParams struct {
	Zone string
	ID   string
}

// PrivateHostOpCreateParams is parameters of PrivateHostOp_create operation.
type PrivateHostOpCreateParams struct {
	Zone string
}

// PrivateHostOpDeleteParams is parameters of PrivateHostOp_delete operation.
type PrivateHostOpDeleteParams struct {
	Zone string
	ID   string
}

// PrivateHostOpFindParams is parameters of PrivateHostOp_find operation.
type PrivateHostOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合
	// - `Tags` (string[]): タグ完全一致の AND 結合.
	Q OptString `json:",omitempty,omitzero"`
}

// PrivateHostOpReadParams is parameters of PrivateHostOp_read operation.
type PrivateHostOpReadParams struct {
	Zone string
	ID   string
}

// PrivateHostOpUpdateParams is parameters of PrivateHostOp_update operation.
type PrivateHostOpUpdateParams struct {
	Zone string
	ID   string
}

// PrivateHostPlanOpFindParams is parameters of PrivateHostPlanOp_find operation.
type PrivateHostPlanOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合
	// - `Class` (string): Appliance のサブクラス（例 `database` /
	// `loadbalancer`）の部分一致.
	Q OptString `json:",omitempty,omitzero"`
}

// PrivateHostPlanOpReadParams is parameters of PrivateHostPlanOp_read operation.
type PrivateHostPlanOpReadParams struct {
	Zone string
	ID   string
}

// ProxyLBOpChangePlanParams is parameters of ProxyLBOp_changePlan operation.
type ProxyLBOpChangePlanParams struct {
	Zone string
	ID   string
}

// ProxyLBOpDeleteCertificatesParams is parameters of ProxyLBOp_deleteCertificates operation.
type ProxyLBOpDeleteCertificatesParams struct {
	Zone string
	ID   string
}

// ProxyLBOpGetCertificatesParams is parameters of ProxyLBOp_getCertificates operation.
type ProxyLBOpGetCertificatesParams struct {
	Zone string
	ID   string
}

// ProxyLBOpMonitorConnectionParams is parameters of ProxyLBOp_monitorConnection operation.
type ProxyLBOpMonitorConnectionParams struct {
	Zone string
	ID   string
}

// ProxyLBOpRenewLetsEncryptCertParams is parameters of ProxyLBOp_renewLetsEncryptCert operation.
type ProxyLBOpRenewLetsEncryptCertParams struct {
	Zone string
	ID   string
}

// ProxyLBOpSetCertificatesParams is parameters of ProxyLBOp_setCertificates operation.
type ProxyLBOpSetCertificatesParams struct {
	Zone string
	ID   string
}

// RegionOpFindParams is parameters of RegionOp_find operation.
type RegionOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合.
	Q OptString `json:",omitempty,omitzero"`
}

// RegionOpReadParams is parameters of RegionOp_read operation.
type RegionOpReadParams struct {
	Zone string
	ID   string
}

// SIMOpActivateParams is parameters of SIMOp_activate operation.
type SIMOpActivateParams struct {
	Zone string
	ID   string
}

// SIMOpAssignIPParams is parameters of SIMOp_assignIP operation.
type SIMOpAssignIPParams struct {
	Zone string
	ID   string
}

// SIMOpClearIPParams is parameters of SIMOp_clearIP operation.
type SIMOpClearIPParams struct {
	Zone string
	ID   string
}

// SIMOpDeactivateParams is parameters of SIMOp_deactivate operation.
type SIMOpDeactivateParams struct {
	Zone string
	ID   string
}

// SIMOpGetNetworkOperatorParams is parameters of SIMOp_getNetworkOperator operation.
type SIMOpGetNetworkOperatorParams struct {
	Zone string
	ID   string
}

// SIMOpImeiLockParams is parameters of SIMOp_imeiLock operation.
type SIMOpImeiLockParams struct {
	Zone string
	ID   string
}

// SIMOpImeiUnlockParams is parameters of SIMOp_imeiUnlock operation.
type SIMOpImeiUnlockParams struct {
	Zone string
	ID   string
}

// SIMOpLogsParams is parameters of SIMOp_logs operation.
type SIMOpLogsParams struct {
	Zone string
	ID   string
}

// SIMOpMonitorSIMParams is parameters of SIMOp_monitorSIM operation.
type SIMOpMonitorSIMParams struct {
	Zone string
	ID   string
}

// SIMOpSetNetworkOperatorParams is parameters of SIMOp_setNetworkOperator operation.
type SIMOpSetNetworkOperatorParams struct {
	Zone string
	ID   string
}

// SSHKeyOpCreateParams is parameters of SSHKeyOp_create operation.
type SSHKeyOpCreateParams struct {
	Zone string
}

// SSHKeyOpDeleteParams is parameters of SSHKeyOp_delete operation.
type SSHKeyOpDeleteParams struct {
	Zone string
	ID   string
}

// SSHKeyOpFindParams is parameters of SSHKeyOp_find operation.
type SSHKeyOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合.
	Q OptString `json:",omitempty,omitzero"`
}

// SSHKeyOpReadParams is parameters of SSHKeyOp_read operation.
type SSHKeyOpReadParams struct {
	Zone string
	ID   string
}

// SSHKeyOpUpdateParams is parameters of SSHKeyOp_update operation.
type SSHKeyOpUpdateParams struct {
	Zone string
	ID   string
}

// ServerOpBootParams is parameters of ServerOp_boot operation.
type ServerOpBootParams struct {
	Zone string
	ID   string
}

// ServerOpChangePlanParams is parameters of ServerOp_changePlan operation.
type ServerOpChangePlanParams struct {
	Zone string
	ID   string
}

// ServerOpCreateParams is parameters of ServerOp_create operation.
type ServerOpCreateParams struct {
	Zone string
}

// ServerOpDeleteParams is parameters of ServerOp_delete operation.
type ServerOpDeleteParams struct {
	Zone string
	ID   string
}

// ServerOpEjectCDROMParams is parameters of ServerOp_ejectCDROM operation.
type ServerOpEjectCDROMParams struct {
	Zone string
	ID   string
}

// ServerOpFindParams is parameters of ServerOp_find operation.
type ServerOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合
	// - `Tags` (string[]): タグ完全一致の AND 結合.
	Q OptString `json:",omitempty,omitzero"`
}

// ServerOpGetVNCProxyParams is parameters of ServerOp_getVNCProxy operation.
type ServerOpGetVNCProxyParams struct {
	Zone string
	ID   string
}

// ServerOpInsertCDROMParams is parameters of ServerOp_insertCDROM operation.
type ServerOpInsertCDROMParams struct {
	Zone string
	ID   string
}

// ServerOpMonitorParams is parameters of ServerOp_monitor operation.
type ServerOpMonitorParams struct {
	Zone string
	ID   string
}

// ServerOpReadParams is parameters of ServerOp_read operation.
type ServerOpReadParams struct {
	Zone string
	ID   string
}

// ServerOpResetParams is parameters of ServerOp_reset operation.
type ServerOpResetParams struct {
	Zone string
	ID   string
}

// ServerOpSendKeyParams is parameters of ServerOp_sendKey operation.
type ServerOpSendKeyParams struct {
	Zone string
	ID   string
}

// ServerOpSendNMIParams is parameters of ServerOp_sendNMI operation.
type ServerOpSendNMIParams struct {
	Zone string
	ID   string
}

// ServerOpShutdownParams is parameters of ServerOp_shutdown operation.
type ServerOpShutdownParams struct {
	Zone string
	ID   string
}

// ServerOpUpdateParams is parameters of ServerOp_update operation.
type ServerOpUpdateParams struct {
	Zone string
	ID   string
}

// ServerPlanOpFindParams is parameters of ServerPlanOp_find operation.
type ServerPlanOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合.
	Q OptString `json:",omitempty,omitzero"`
}

// ServerPlanOpReadParams is parameters of ServerPlanOp_read operation.
type ServerPlanOpReadParams struct {
	Zone string
	ID   string
}

// ServiceClassOpFindParams is parameters of ServiceClassOp_find operation.
type ServiceClassOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合.
	Q OptString `json:",omitempty,omitzero"`
}

// SimpleMonitorOpMonitorResponseTimeParams is parameters of SimpleMonitorOp_monitorResponseTime operation.
type SimpleMonitorOpMonitorResponseTimeParams struct {
	Zone string
	ID   string
}

// SimpleNotificationGroupOpHistoryParams is parameters of SimpleNotificationGroupOp_history operation.
type SimpleNotificationGroupOpHistoryParams struct {
	Zone string
}

// SimpleNotificationGroupOpPostMessageParams is parameters of SimpleNotificationGroupOp_postMessage operation.
type SimpleNotificationGroupOpPostMessageParams struct {
	Zone string
	ID   string
}

// SubnetOpFindParams is parameters of SubnetOp_find operation.
type SubnetOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合.
	Q OptString `json:",omitempty,omitzero"`
}

// SubnetOpReadParams is parameters of SubnetOp_read operation.
type SubnetOpReadParams struct {
	Zone string
	ID   string
}

// SwitchOpConnectToBridgeParams is parameters of SwitchOp_connectToBridge operation.
type SwitchOpConnectToBridgeParams struct {
	Zone     string
	ID       string
	BridgeID string
}

// SwitchOpCreateParams is parameters of SwitchOp_create operation.
type SwitchOpCreateParams struct {
	Zone string
}

// SwitchOpDeleteParams is parameters of SwitchOp_delete operation.
type SwitchOpDeleteParams struct {
	Zone string
	ID   string
}

// SwitchOpDisconnectFromBridgeParams is parameters of SwitchOp_disconnectFromBridge operation.
type SwitchOpDisconnectFromBridgeParams struct {
	Zone string
	ID   string
}

// SwitchOpFindParams is parameters of SwitchOp_find operation.
type SwitchOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合
	// - `Tags` (string[]): タグ完全一致の AND 結合
	// - `Scope` (string): `"shared"` または `"user"` の部分一致.
	Q OptString `json:",omitempty,omitzero"`
}

// SwitchOpGetServersParams is parameters of SwitchOp_getServers operation.
type SwitchOpGetServersParams struct {
	Zone string
	ID   string
}

// SwitchOpReadParams is parameters of SwitchOp_read operation.
type SwitchOpReadParams struct {
	Zone string
	ID   string
}

// SwitchOpUpdateParams is parameters of SwitchOp_update operation.
type SwitchOpUpdateParams struct {
	Zone string
	ID   string
}

// VPCRouterOpConnectToSwitchParams is parameters of VPCRouterOp_connectToSwitch operation.
type VPCRouterOpConnectToSwitchParams struct {
	Zone     string
	ID       string
	NicIndex string
	SwitchID string
}

// VPCRouterOpDisconnectFromSwitchParams is parameters of VPCRouterOp_disconnectFromSwitch operation.
type VPCRouterOpDisconnectFromSwitchParams struct {
	Zone     string
	ID       string
	NicIndex string
}

// VPCRouterOpPingParams is parameters of VPCRouterOp_ping operation.
type VPCRouterOpPingParams struct {
	Zone        string
	ID          string
	Destination string
}

// ZoneOpFindParams is parameters of ZoneOp_find operation.
type ZoneOpFindParams struct {
	Zone string
	// Find 検索条件をシリアライズした JSON 文字列を渡す。
	// **指定可能なトップレベルフィールド:**
	// - `Count` (int): 取得件数の上限
	// - `From` (int): 開始オフセット
	// - `Filter` (object): このエンドポイントで指定可能なフィルタキーは以下
	// - `Name` (string): 部分一致。スペース区切りで AND 結合.
	Q OptString `json:",omitempty,omitzero"`
}

// ZoneOpReadParams is parameters of ZoneOp_read operation.
type ZoneOpReadParams struct {
	Zone string
	ID   string
}
