// Code generated by ogen, DO NOT EDIT.

package client

// setDefaults set default value of fields.
func (s *ProxyLBSyslog) setDefaults() {
	{
		val := int32(514)
		s.Port = val
	}
}

// setDefaults set default value of fields.
func (s *ProxyLBTimeout) setDefaults() {
	{
		val := int32(10)
		s.InactiveSec = val
	}
}
