// Copyright 2022-2025 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "stringer -type=ArchiveOSType"; DO NOT EDIT.

package ostype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Custom-0]
	_ = x[AlmaLinux-1]
	_ = x[AlmaLinux9-2]
	_ = x[AlmaLinux8-3]
	_ = x[RockyLinux-4]
	_ = x[RockyLinux9-5]
	_ = x[RockyLinux8-6]
	_ = x[MiracleLinux-7]
	_ = x[MiracleLinux8-8]
	_ = x[MiracleLinux9-9]
	_ = x[Ubuntu-10]
	_ = x[Ubuntu2404-11]
	_ = x[Ubuntu2204-12]
	_ = x[Debian-13]
	_ = x[Debian11-14]
	_ = x[Debian12-15]
	_ = x[Kusanagi-16]
}

const _ArchiveOSType_name = "CustomAlmaLinuxAlmaLinux9AlmaLinux8RockyLinuxRockyLinux9RockyLinux8MiracleLinuxMiracleLinux8MiracleLinux9UbuntuUbuntu2404Ubuntu2204DebianDebian11Debian12Kusanagi"

var _ArchiveOSType_index = [...]uint8{0, 6, 15, 25, 35, 45, 56, 67, 79, 92, 105, 111, 121, 131, 137, 145, 153, 161}

func (i ArchiveOSType) String() string {
	if i < 0 || i >= ArchiveOSType(len(_ArchiveOSType_index)-1) {
		return "ArchiveOSType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArchiveOSType_name[_ArchiveOSType_index[i]:_ArchiveOSType_index[i+1]]
}
