// Copyright 2022-2025 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "stringer -type=ArchiveOSType"; DO NOT EDIT.

package ostype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Custom-0]
	_ = x[AlmaLinux-1]
	_ = x[AlmaLinux10-2]
	_ = x[AlmaLinux9-3]
	_ = x[RockyLinux-4]
	_ = x[RockyLinux10-5]
	_ = x[RockyLinux9-6]
	_ = x[MiracleLinux-7]
	_ = x[MiracleLinux8-8]
	_ = x[MiracleLinux9-9]
	_ = x[Ubuntu-10]
	_ = x[Ubuntu2404-11]
	_ = x[Ubuntu2204-12]
	_ = x[Debian-13]
	_ = x[Debian11-14]
	_ = x[Debian12-15]
	_ = x[Kusanagi-16]
}

const _ArchiveOSType_name = "CustomAlmaLinuxAlmaLinux10AlmaLinux9RockyLinuxRockyLinux10RockyLinux9MiracleLinuxMiracleLinux8MiracleLinux9UbuntuUbuntu2404Ubuntu2204DebianDebian11Debian12Kusanagi"

var _ArchiveOSType_index = [...]uint8{0, 6, 15, 26, 36, 46, 58, 69, 81, 94, 107, 113, 123, 133, 139, 147, 155, 163}

func (i ArchiveOSType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ArchiveOSType_index)-1 {
		return "ArchiveOSType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArchiveOSType_name[_ArchiveOSType_index[idx]:_ArchiveOSType_index[idx+1]]
}
