// Copyright 2022 The sacloud/iaas-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "stringer -type=ArchiveOSType"; DO NOT EDIT.

package ostype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Custom-0]
	_ = x[CentOS-1]
	_ = x[CentOS7-2]
	_ = x[AlmaLinux-3]
	_ = x[RockyLinux-4]
	_ = x[MiracleLinux-5]
	_ = x[Ubuntu-6]
	_ = x[Ubuntu2204-7]
	_ = x[Ubuntu2004-8]
	_ = x[Ubuntu1804-9]
	_ = x[Debian-10]
	_ = x[Debian10-11]
	_ = x[Debian11-12]
	_ = x[Kusanagi-13]
}

const _ArchiveOSType_name = "CustomCentOSCentOS7AlmaLinuxRockyLinuxMiracleLinuxUbuntuUbuntu2204Ubuntu2004Ubuntu1804DebianDebian10Debian11Kusanagi"

var _ArchiveOSType_index = [...]uint8{0, 6, 12, 19, 28, 38, 50, 56, 66, 76, 86, 92, 100, 108, 116}

func (i ArchiveOSType) String() string {
	if i < 0 || i >= ArchiveOSType(len(_ArchiveOSType_index)-1) {
		return "ArchiveOSType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArchiveOSType_name[_ArchiveOSType_index[i]:_ArchiveOSType_index[i+1]]
}
